package com.ky.ct.rzdj.util;

import com.ky.ct.rzdj.model.BaseFpxexd;
import com.ky.ct.rzdj.model.BaseFpxexdHistory;

public class UpdateFpxexd {
    /**
     * 根据身份证号从数据库查询出一个对象
     * 根获取前端传递过来的数据封装数据
     *将前端传递过来数据封装到从数据库中获取的对象中并返回
     */
    public static BaseFpxexdHistory updateSingle(BaseFpxexdHistory f1, BaseFpxexdHistory f2){
        if(f1.getXiang()!=null&&!"".equals(f1.getXiang())){
            f2.setXiang(f1.getXiang());
        }
        if(f1.getChun()!=null&&!"".equals(f1.getChun())){
            f2.setChun(f1.getChun());
        }
        if(f1.getZu()!=null&&!"".equals(f1.getZu())){
            f2.setZu(f1.getZu());
        }
        if(f1.getName()!=null&&!"".equals(f1.getName())){
            f2.setName(f1.getName());
        }
        if(f1.getMembers()!=null&&!"".equals(f1.getMembers())){
            f2.setMembers(f1.getMembers());
        }
        if(f1.getDaiKuanRenXingMing()!=null&&!"".equals(f1.getDaiKuanRenXingMing())){
            f2.setDaiKuanRenXingMing(f1.getDaiKuanRenXingMing());
        }
        if(f1.getDaiKuanRenCardId()!=null&&!"".equals(f1.getDaiKuanRenCardId())){
            f2.setDaiKuanRenCardId(f1.getDaiKuanRenCardId());
        }
        if(f1.getFamilyRelation()!=null&&!"".equals(f1.getFamilyRelation())){
            f2.setFamilyRelation(f1.getFamilyRelation());
        }
        if(f1.getTuoPinState()!=null&&!"".equals(f1.getTuoPinState())){
            f2.setTuoPinState(f1.getTuoPinState());
        }
        if(f1.getYuanYouYuE()!=null&&!"".equals(f1.getYuanYouYuE())){
            f2.setYuanYouYuE(f1.getYuanYouYuE());
        }
        if(f1.getYuanYouIsYuQi()!=null&&!"".equals(f1.getYuanYouIsYuQi())){
            f2.setYuanYouIsYuQi(f1.getYuanYouIsYuQi());
        }
        if(f1.getYuanYouYuQiJinE()!=null&&!"".equals(f1.getYuanYouYuQiJinE())){
            f2.setYuanYouYuQiJinE(f1.getYuanYouYuQiJinE());
        }
        if(f1.getYuanYouYuQiShiJian()!=null&&!"".equals(f1.getYuanYouYuQiShiJian())){
            f2.setYuanYouYuQiShiJian(f1.getYuanYouYuQiShiJian());
        }
        if(f1.getYuanYouQianXiJinE()!=null&&!"".equals(f1.getYuanYouQianXiJinE())){
            f2.setYuanYouQianXiJinE(f1.getYuanYouQianXiJinE());
        }
        if(f1.getYuanYouQianXiShiJian()!=null&&!"".equals(f1.getYuanYouQianXiShiJian())){
            f2.setYuanYouQianXiShiJian(f1.getYuanYouQianXiShiJian());
        }
        if(f1.getFuPingivenStars()!=null&&!"".equals(f1.getFuPingivenStars())){
            f2.setFuPingivenStars(f1.getFuPingivenStars());
        }
        if(f1.getFuPinshouXinEDu()!=null&&!"".equals(f1.getFuPinshouXinEDu())){
            f2.setFuPinshouXinEDu(f1.getFuPinshouXinEDu());
        }
        if(f1.getFuPinshouXinJiGou()!=null&&!"".equals(f1.getFuPinshouXinJiGou())){
            f2.setFuPinshouXinJiGou(f1.getFuPinshouXinJiGou());
        }
        if(f1.getFuPinshouxinData()!=null&&!"".equals(f1.getFuPinshouxinData())){
            f2.setFuPinshouxinData(f1.getFuPinshouxinData());
        }
        if(f1.getFuPinXiaoDaidaiKuanJinE()!=null&&!"".equals(f1.getFuPinXiaoDaidaiKuanJinE())){
            f2.setFuPinXiaoDaidaiKuanJinE(f1.getFuPinXiaoDaidaiKuanJinE());
        }
        if(f1.getFuPindaiKuanQiXian()!=null&&!"".equals(f1.getFuPindaiKuanQiXian())){
            f2.setFuPindaiKuanQiXian(f1.getFuPindaiKuanQiXian());
        }
        if(f1.getFuPinfangKuanRiQi()!=null&&!"".equals(f1.getFuPinfangKuanRiQi())){
            f2.setFuPinfangKuanRiQi(f1.getFuPinfangKuanRiQi());
        }
        if(f1.getFuPindaoQiRiQi()!=null&&!"".equals(f1.getFuPindaoQiRiQi())){
            f2.setFuPindaoQiRiQi(f1.getFuPindaoQiRiQi());
        }
        if(f1.getFuPinXiaoDaiDaiKuanLiLv()!=null&&!"".equals(f1.getFuPinXiaoDaiDaiKuanLiLv())){
            f2.setFuPinXiaoDaiDaiKuanLiLv(f1.getFuPinXiaoDaiDaiKuanLiLv());
        }
        if(f1.getFuPindaiKuanJiGou()!=null&&!"".equals(f1.getFuPindaiKuanJiGou())){
            f2.setFuPindaiKuanJiGou(f1.getFuPindaiKuanJiGou());
        }
        if(f1.getFuPinleiJiTieXi()!=null&&!"".equals(f1.getFuPinleiJiTieXi())){
            f2.setFuPinleiJiTieXi(f1.getFuPinleiJiTieXi());
        }
        if(f1.getFuPinchangHuanDaiKuanJInE()!=null&&!"".equals(f1.getFuPinchangHuanDaiKuanJInE())){
            f2.setFuPinchangHuanDaiKuanJInE(f1.getFuPinchangHuanDaiKuanJInE());
        }
        if(f1.getFuPinhuanKuanShiJian()!=null&&!"".equals(f1.getFuPinhuanKuanShiJian())){
            f2.setFuPinhuanKuanShiJian(f1.getFuPinhuanKuanShiJian());
        }
        if(f1.getFuPindaiKuanYuE()!=null&&!"".equals(f1.getFuPindaiKuanYuE())){
            f2.setFuPindaiKuanYuE(f1.getFuPindaiKuanYuE());
        }
        if(f1.getFuPinyuQiDaiKuanJinE()!=null&&!"".equals(f1.getFuPinyuQiDaiKuanJinE())){
            f2.setFuPinyuQiDaiKuanJinE(f1.getFuPinyuQiDaiKuanJinE());
        }
        if(f1.getFuPinyuQiDaiKuanShiJian()!=null&&!"".equals(f1.getFuPinyuQiDaiKuanShiJian())){
            f2.setFuPinyuQiDaiKuanShiJian(f1.getFuPinyuQiDaiKuanShiJian());
        }
        if(f1.getFuPinqianXiJinE()!=null&&!"".equals(f1.getFuPinqianXiJinE())){
            f2.setFuPinqianXiJinE(f1.getFuPinqianXiJinE());
        }
        if(f1.getFuPinqianXiShiJian()!=null&&!"".equals(f1.getFuPinqianXiShiJian())){
            f2.setFuPinqianXiShiJian(f1.getFuPinqianXiShiJian());
        }
        if(f1.getFuPinYingDaiWeiDaiShiBie()!=null&&!"".equals(f1.getFuPinYingDaiWeiDaiShiBie())){
            f2.setFuPinYingDaiWeiDaiShiBie(f1.getFuPinYingDaiWeiDaiShiBie());
        }
        if(f1.getFuPinDaiKuanYongTu()!=null&&!"".equals(f1.getFuPinDaiKuanYongTu())){
            f2.setFuPinDaiKuanYongTu(f1.getFuPinDaiKuanYongTu());
        }
        if(f1.getChuangYeJinE()!=null&&!"".equals(f1.getChuangYeJinE())){
            f2.setChuangYeJinE(f1.getChuangYeJinE());
        }
        if(f1.getChuangYeQiXian()!=null&&!"".equals(f1.getChuangYeQiXian())){
            f2.setChuangYeQiXian(f1.getChuangYeQiXian());
        }
        if(f1.getChuangYeFangKuanRiQi()!=null&&!"".equals(f1.getChuangYeFangKuanRiQi())){
            f2.setChuangYeFangKuanRiQi(f1.getChuangYeFangKuanRiQi());
        }
        if(f1.getChuangYeDaoQiShiJian()!=null&&!"".equals(f1.getChuangYeDaoQiShiJian())){
            f2.setChuangYeDaoQiShiJian(f1.getChuangYeDaoQiShiJian());
        }
        if(f1.getChuangYeLiLv()!=null&&!"".equals(f1.getChuangYeLiLv())){
            f2.setChuangYeLiLv(f1.getChuangYeLiLv());
        }
        if(f1.getChuangYeChangHuanJinE()!=null&&!"".equals(f1.getChuangYeChangHuanJinE())){
            f2.setChuangYeChangHuanJinE(f1.getChuangYeChangHuanJinE());
        }
        if(f1.getChangYeHuangKuanShiJian()!=null&&!"".equals(f1.getChangYeHuangKuanShiJian())){
            f2.setChangYeHuangKuanShiJian(f1.getChangYeHuangKuanShiJian());
        }
        if(f1.getChuangYeYuE()!=null&&!"".equals(f1.getChuangYeYuE())){
            f2.setChuangYeYuE(f1.getChuangYeYuE());
        }
        if(f1.getChuangYeYuQiJinE()!=null&&!"".equals(f1.getChuangYeYuQiJinE())){
            f2.setChuangYeYuQiJinE(f1.getChuangYeYuQiJinE());
        }
        if(f1.getChuangYeYuQiShiJian()!=null&&!"".equals(f1.getChuangYeYuQiShiJian())){
            f2.setChuangYeYuQiShiJian(f1.getChuangYeYuQiShiJian());
        }
        if(f1.getChuangYeQianXiJinE()!=null&&!"".equals(f1.getChuangYeQianXiJinE())){
            f2.setChuangYeQianXiJinE(f1.getChuangYeQianXiJinE());
        }
        if(f1.getChuangYeQianXiShiJian()!=null&&!"".equals(f1.getChuangYeQianXiShiJian())){
            f2.setChuangYeQianXiShiJian(f1.getChuangYeQianXiShiJian());
        }
        if(f1.getChuangYeYongTu()!=null&&!"".equals(f1.getChuangYeYongTu())){
            f2.setChuangYeYongTu(f1.getChuangYeYongTu());
        }
        if(f1.getShengYuanJinE()!=null&&!"".equals(f1.getShengYuanJinE())){
            f2.setShengYuanJinE(f1.getShengYuanJinE());
        }
        if(f1.getShengYuanQiXian()!=null&&!"".equals(f1.getShengYuanQiXian())){
            f2.setShengYuanQiXian(f1.getShengYuanQiXian());
        }
        if(f1.getShengYuanFangKuanRiQi()!=null&&!"".equals(f1.getShengYuanFangKuanRiQi())){
            f2.setShengYuanFangKuanRiQi(f1.getShengYuanFangKuanRiQi());
        }
        if(f1.getShengYaunDaoQiRiQi()!=null&&!"".equals(f1.getShengYaunDaoQiRiQi())){
            f2.setShengYaunDaoQiRiQi(f1.getShengYaunDaoQiRiQi());
        }
        if(f1.getShengYaunLiLv()!=null&&!"".equals(f1.getShengYaunLiLv())){
            f2.setShengYaunLiLv(f1.getShengYaunLiLv());
        }
        if(f1.getShengYaunChangHuanJinE()!=null&&!"".equals(f1.getShengYaunChangHuanJinE())){
            f2.setShengYaunChangHuanJinE(f1.getShengYaunChangHuanJinE());
        }
        if(f1.getShengYuanHuanKuanShiJian()!=null&&!"".equals(f1.getShengYuanHuanKuanShiJian())){
            f2.setShengYuanHuanKuanShiJian(f1.getShengYuanHuanKuanShiJian());
        }
        if(f1.getShengYuanYuE()!=null&&!"".equals(f1.getShengYuanYuE())){
            f2.setShengYuanYuE(f1.getShengYuanYuE());
        }
        if(f1.getShengYuanYuQiJinE()!=null&&!"".equals(f1.getShengYuanYuQiJinE())){
            f2.setShengYuanYuQiJinE(f1.getShengYuanYuQiJinE());
        }
        if(f1.getShengYuanYuQiShiJian()!=null&&!"".equals(f1.getShengYuanYuQiShiJian())){
            f2.setShengYuanYuQiShiJian(f1.getShengYuanYuQiShiJian());
        }
        if(f1.getShengYuanQianXiJinE()!=null&&!"".equals(f1.getShengYuanQianXiJinE())){
            f2.setShengYuanQianXiJinE(f1.getShengYuanQianXiJinE());
        }
        if(f1.getShengYuanQianXiShiJian()!=null&&!"".equals(f1.getShengYuanQianXiShiJian())){
            f2.setShengYuanQianXiShiJian(f1.getShengYuanQianXiShiJian());
        }
        if(f1.getQiTaJinE()!=null&&!"".equals(f1.getQiTaJinE())){
            f2.setQiTaJinE(f1.getQiTaJinE());
        }
        if(f1.getQiTaQiXian()!=null&&!"".equals(f1.getQiTaQiXian())){
            f2.setQiTaQiXian(f1.getQiTaQiXian());
        }
        if(f1.getQiTaFangKuanRiQi()!=null&&!"".equals(f1.getQiTaFangKuanRiQi())){
            f2.setQiTaFangKuanRiQi(f1.getQiTaFangKuanRiQi());
        }
        if(f1.getQiTaDaoQiRiQi()!=null&&!"".equals(f1.getQiTaDaoQiRiQi())){
            f2.setQiTaDaoQiRiQi(f1.getQiTaDaoQiRiQi());
        }
        if(f1.getQiTaLiLv()!=null&&!"".equals(f1.getQiTaLiLv())){
            f2.setQiTaLiLv(f1.getQiTaLiLv());
        }
        if(f1.getQiTaChangHuanJinE()!=null&&!"".equals(f1.getQiTaChangHuanJinE())){
            f2.setQiTaChangHuanJinE(f1.getQiTaChangHuanJinE());
        }
        if(f1.getQiTaChangHuangKuanShiJian()!=null&&!"".equals(f1.getQiTaChangHuangKuanShiJian())){
            f2.setQiTaChangHuangKuanShiJian(f1.getQiTaChangHuangKuanShiJian());
        }
        if(f1.getQiTaYuE()!=null&&!"".equals(f1.getQiTaYuE())){
            f2.setQiTaYuE(f1.getQiTaYuE());
        }
        if(f1.getQiTaYuQiJinE()!=null&&!"".equals(f1.getQiTaYuQiJinE())){
            f2.setQiTaYuQiJinE(f1.getQiTaYuQiJinE());
        }
        if(f1.getQiTaYuQiShiJian()!=null&&!"".equals(f1.getQiTaYuQiShiJian())){
            f2.setQiTaYuQiShiJian(f1.getQiTaYuQiShiJian());
        }
        if(f1.getQiTaQianXiJinE()!=null&&!"".equals(f1.getQiTaQianXiJinE())){
            f2.setQiTaQianXiJinE(f1.getQiTaQianXiJinE());
        }
        if(f1.getQiTaQianXiShiJian()!=null&&!"".equals(f1.getQiTaQianXiShiJian())){
            f2.setQiTaQianXiShiJian(f1.getQiTaQianXiShiJian());
        }
        if(f1.getQiTaYongTu()!=null&&!"".equals(f1.getQiTaYongTu())){
            f2.setQiTaYongTu(f1.getQiTaYongTu());
        }
        if(f1.getNote()!=null&&!"".equals(f1.getNote())){
            f2.setNote(f1.getNote());
        }
        return f2;
    }
}
