package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Auditprojectreport generated by hbm2java
 */
@Entity
@Table(name = "auditprojectreport", catalog = "audit", uniqueConstraints = @UniqueConstraint(columnNames = "year"))
public class AuditProjectReport implements java.io.Serializable {

	private Integer id;
	private int year;
	private int state;
	private String sumbitOne;
	private String sumbitDate;
	private String name;
	private int editDpt;

	public AuditProjectReport() {
	}

	public AuditProjectReport(int year, int state, String sumbitOne, String name, int editDpt) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.name = name;
		this.editDpt = editDpt;
	}

	public AuditProjectReport(int year, int state, String sumbitOne, String sumbitDate, String name, int editDpt) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.sumbitDate = sumbitDate;
		this.name = name;
		this.editDpt = editDpt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year", unique = true, nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "sumbitOne", nullable = false, length = 12)
	public String getSumbitOne() {
		return this.sumbitOne;
	}

	public void setSumbitOne(String sumbitOne) {
		this.sumbitOne = sumbitOne;
	}

	@Column(name = "sumbitDate", length = 32)
	public String getSumbitDate() {
		return this.sumbitDate;
	}

	public void setSumbitDate(String sumbitDate) {
		this.sumbitDate = sumbitDate;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "editDpt", nullable = false)
	public int getEditDpt() {
		return this.editDpt;
	}

	public void setEditDpt(int editDpt) {
		this.editDpt = editDpt;
	}

}
