package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Auditproject generated by hbm2java
 */
@Entity
@Table(name = "auditproject", catalog = "audit")
public class AuditProject implements java.io.Serializable {

	private Integer id;
	private Integer year;
	private String projectName;
	private String type;
	private String projectDpt;
	private String projectKz;
	private String projectZs;
	private String projectCy;
	private String start;
	private String end;
	private int workDays;
	private String remark;

	public AuditProject() {
	}

	public AuditProject(String projectName, String type, String projectDpt, String projectKz, String projectZs,
			String projectCy, int workDays) {
		this.projectName = projectName;
		this.type = type;
		this.projectDpt = projectDpt;
		this.projectKz = projectKz;
		this.projectZs = projectZs;
		this.projectCy = projectCy;
		this.workDays = workDays;
	}

	public AuditProject(Integer year, String projectName, String type, String projectDpt, String projectKz,
			String projectZs, String projectCy, String start, String end, int workDays, String remark) {
		this.year = year;
		this.projectName = projectName;
		this.type = type;
		this.projectDpt = projectDpt;
		this.projectKz = projectKz;
		this.projectZs = projectZs;
		this.projectCy = projectCy;
		this.start = start;
		this.end = end;
		this.workDays = workDays;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "projectName", nullable = false, length = 200)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "type", nullable = false, length = 12)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "projectDpt", nullable = false, length = 32)
	public String getProjectDpt() {
		return this.projectDpt;
	}

	public void setProjectDpt(String projectDpt) {
		this.projectDpt = projectDpt;
	}

	@Column(name = "projectKZ", nullable = false, length = 12)
	public String getProjectKz() {
		return this.projectKz;
	}

	public void setProjectKz(String projectKz) {
		this.projectKz = projectKz;
	}

	@Column(name = "projectZS", nullable = false, length = 12)
	public String getProjectZs() {
		return this.projectZs;
	}

	public void setProjectZs(String projectZs) {
		this.projectZs = projectZs;
	}

	@Column(name = "projectCY", nullable = false, length = 64)
	public String getProjectCy() {
		return this.projectCy;
	}

	public void setProjectCy(String projectCy) {
		this.projectCy = projectCy;
	}

	@Column(name = "start", length = 128)
	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	@Column(name = "end", length = 128)
	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	@Column(name = "workDays", nullable = false)
	public int getWorkDays() {
		return this.workDays;
	}

	public void setWorkDays(int workDays) {
		this.workDays = workDays;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
