package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Auditpersonreport generated by hbm2java
 */
@Entity
@Table(name = "auditpersonreport", catalog = "audit", uniqueConstraints = @UniqueConstraint(columnNames = "year"))
public class AuditPersonReport implements java.io.Serializable {

	private Integer id;
	private int year;
	private int state;
	private String sumbitOne;
	private String sumbitDate;
	private String name;
	private int editDpt;
	private String dptName;
	private Integer fzjgs;
	private Integer zmjg;
	private Integer hsbg;
	private Integer zhuanZhi;
	private Integer jianZhi;
	private Integer ryzs;
	private String zhanBi;
	private Integer rydrs;
	private Integer rydcs;
	private Integer boShi;
	private Integer shuoShi;
	private Integer benKe;
	private Integer qiTa;
	private Integer pjnl;
	private Integer yiXia;
	private Integer yiShang;
	private Integer gjzc;
	private Integer zjzc;
	private Integer cjzc;
	private Integer cia;
	private Integer cpa;
	private Integer qtzg;
	private Integer fzjgs2;
	private Integer zmjg2;
	private Integer hsbg2;
	private Integer zhuanZhi2;
	private Integer jianZhi2;
	private Integer ryzs2;
	private String zhanBi2;
	private Integer rydrs2;
	private Integer rydcs2;
	private Integer boShi2;
	private Integer shuoShi2;
	private Integer benKe2;
	private Integer qiTa2;
	private Integer pjnl2;
	private Integer yiXia2;
	private Integer yiShang2;
	private Integer gjzc2;
	private Integer zjzc2;
	private Integer cjzc2;
	private Integer cia2;
	private Integer cpa2;
	private Integer qtzg2;
	private Integer fzjgs3;
	private Integer zmjg3;
	private Integer hsbg3;
	private Integer zhuanZhi3;
	private Integer jianZhi3;
	private Integer ryzs3;
	private String zhanBi3;
	private Integer rydrs3;
	private Integer rydcs3;
	private Integer boShi3;
	private Integer shuoShi3;
	private Integer benKe3;
	private Integer qiTa3;
	private Integer pjnl3;
	private Integer yiXia3;
	private Integer yiShang3;
	private Integer gjzc3;
	private Integer zjzc3;
	private Integer cjzc3;
	private Integer cia3;
	private Integer cpa3;
	private Integer qtzg3;
	private Integer fzjgs4;
	private Integer zmjg4;
	private Integer hsbg4;
	private Integer zhuanZhi4;
	private Integer jianZhi4;
	private Integer ryzs4;
	private String zhanBi4;
	private Integer rydrs4;
	private Integer rydcs4;
	private Integer boShi4;
	private Integer shuoShi4;
	private Integer benKe4;
	private Integer qiTa4;
	private Integer pjnl4;
	private Integer yiXia4;
	private Integer yiShang4;
	private Integer gjzc4;
	private Integer zjzc4;
	private Integer cjzc4;
	private Integer cia4;
	private Integer cpa4;
	private Integer qtzg4;
	private String bkzb;
	private String bkzb2;
	private String bkzb3;
	private String bkzb4;

	public AuditPersonReport() {
	}

	public AuditPersonReport(int year, int state, String sumbitOne, String name, int editDpt) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.name = name;
		this.editDpt = editDpt;
	}

	public AuditPersonReport(int year, int state, String sumbitOne, String sumbitDate, String name, int editDpt,
			String dptName, Integer fzjgs, Integer zmjg, Integer hsbg, Integer zhuanZhi, Integer jianZhi, Integer ryzs,
			String zhanBi, Integer rydrs, Integer rydcs, Integer boShi, Integer shuoShi, Integer benKe, Integer qiTa,
			Integer pjnl, Integer yiXia, Integer yiShang, Integer gjzc, Integer zjzc, Integer cjzc, Integer cia,
			Integer cpa, Integer qtzg, Integer fzjgs2, Integer zmjg2, Integer hsbg2, Integer zhuanZhi2,
			Integer jianZhi2, Integer ryzs2, String zhanBi2, Integer rydrs2, Integer rydcs2, Integer boShi2,
			Integer shuoShi2, Integer benKe2, Integer qiTa2, Integer pjnl2, Integer yiXia2, Integer yiShang2,
			Integer gjzc2, Integer zjzc2, Integer cjzc2, Integer cia2, Integer cpa2, Integer qtzg2, Integer fzjgs3,
			Integer zmjg3, Integer hsbg3, Integer zhuanZhi3, Integer jianZhi3, Integer ryzs3, String zhanBi3,
			Integer rydrs3, Integer rydcs3, Integer boShi3, Integer shuoShi3, Integer benKe3, Integer qiTa3,
			Integer pjnl3, Integer yiXia3, Integer yiShang3, Integer gjzc3, Integer zjzc3, Integer cjzc3, Integer cia3,
			Integer cpa3, Integer qtzg3, Integer fzjgs4, Integer zmjg4, Integer hsbg4, Integer zhuanZhi4,
			Integer jianZhi4, Integer ryzs4, String zhanBi4, Integer rydrs4, Integer rydcs4, Integer boShi4,
			Integer shuoShi4, Integer benKe4, Integer qiTa4, Integer pjnl4, Integer yiXia4, Integer yiShang4,
			Integer gjzc4, Integer zjzc4, Integer cjzc4, Integer cia4, Integer cpa4, Integer qtzg4, String bkzb,
			String bkzb2, String bkzb3, String bkzb4) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.sumbitDate = sumbitDate;
		this.name = name;
		this.editDpt = editDpt;
		this.dptName = dptName;
		this.fzjgs = fzjgs;
		this.zmjg = zmjg;
		this.hsbg = hsbg;
		this.zhuanZhi = zhuanZhi;
		this.jianZhi = jianZhi;
		this.ryzs = ryzs;
		this.zhanBi = zhanBi;
		this.rydrs = rydrs;
		this.rydcs = rydcs;
		this.boShi = boShi;
		this.shuoShi = shuoShi;
		this.benKe = benKe;
		this.qiTa = qiTa;
		this.pjnl = pjnl;
		this.yiXia = yiXia;
		this.yiShang = yiShang;
		this.gjzc = gjzc;
		this.zjzc = zjzc;
		this.cjzc = cjzc;
		this.cia = cia;
		this.cpa = cpa;
		this.qtzg = qtzg;
		this.fzjgs2 = fzjgs2;
		this.zmjg2 = zmjg2;
		this.hsbg2 = hsbg2;
		this.zhuanZhi2 = zhuanZhi2;
		this.jianZhi2 = jianZhi2;
		this.ryzs2 = ryzs2;
		this.zhanBi2 = zhanBi2;
		this.rydrs2 = rydrs2;
		this.rydcs2 = rydcs2;
		this.boShi2 = boShi2;
		this.shuoShi2 = shuoShi2;
		this.benKe2 = benKe2;
		this.qiTa2 = qiTa2;
		this.pjnl2 = pjnl2;
		this.yiXia2 = yiXia2;
		this.yiShang2 = yiShang2;
		this.gjzc2 = gjzc2;
		this.zjzc2 = zjzc2;
		this.cjzc2 = cjzc2;
		this.cia2 = cia2;
		this.cpa2 = cpa2;
		this.qtzg2 = qtzg2;
		this.fzjgs3 = fzjgs3;
		this.zmjg3 = zmjg3;
		this.hsbg3 = hsbg3;
		this.zhuanZhi3 = zhuanZhi3;
		this.jianZhi3 = jianZhi3;
		this.ryzs3 = ryzs3;
		this.zhanBi3 = zhanBi3;
		this.rydrs3 = rydrs3;
		this.rydcs3 = rydcs3;
		this.boShi3 = boShi3;
		this.shuoShi3 = shuoShi3;
		this.benKe3 = benKe3;
		this.qiTa3 = qiTa3;
		this.pjnl3 = pjnl3;
		this.yiXia3 = yiXia3;
		this.yiShang3 = yiShang3;
		this.gjzc3 = gjzc3;
		this.zjzc3 = zjzc3;
		this.cjzc3 = cjzc3;
		this.cia3 = cia3;
		this.cpa3 = cpa3;
		this.qtzg3 = qtzg3;
		this.fzjgs4 = fzjgs4;
		this.zmjg4 = zmjg4;
		this.hsbg4 = hsbg4;
		this.zhuanZhi4 = zhuanZhi4;
		this.jianZhi4 = jianZhi4;
		this.ryzs4 = ryzs4;
		this.zhanBi4 = zhanBi4;
		this.rydrs4 = rydrs4;
		this.rydcs4 = rydcs4;
		this.boShi4 = boShi4;
		this.shuoShi4 = shuoShi4;
		this.benKe4 = benKe4;
		this.qiTa4 = qiTa4;
		this.pjnl4 = pjnl4;
		this.yiXia4 = yiXia4;
		this.yiShang4 = yiShang4;
		this.gjzc4 = gjzc4;
		this.zjzc4 = zjzc4;
		this.cjzc4 = cjzc4;
		this.cia4 = cia4;
		this.cpa4 = cpa4;
		this.qtzg4 = qtzg4;
		this.bkzb = bkzb;
		this.bkzb2 = bkzb2;
		this.bkzb3 = bkzb3;
		this.bkzb4 = bkzb4;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year", unique = true, nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "sumbitOne", nullable = false, length = 12)
	public String getSumbitOne() {
		return this.sumbitOne;
	}

	public void setSumbitOne(String sumbitOne) {
		this.sumbitOne = sumbitOne;
	}

	@Column(name = "sumbitDate", length = 32)
	public String getSumbitDate() {
		return this.sumbitDate;
	}

	public void setSumbitDate(String sumbitDate) {
		this.sumbitDate = sumbitDate;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "editDpt", nullable = false)
	public int getEditDpt() {
		return this.editDpt;
	}

	public void setEditDpt(int editDpt) {
		this.editDpt = editDpt;
	}

	@Column(name = "dptName", length = 128)
	public String getDptName() {
		return this.dptName;
	}

	public void setDptName(String dptName) {
		this.dptName = dptName;
	}

	@Column(name = "FZJGS")
	public Integer getFzjgs() {
		return this.fzjgs;
	}

	public void setFzjgs(Integer fzjgs) {
		this.fzjgs = fzjgs;
	}

	@Column(name = "ZMJG")
	public Integer getZmjg() {
		return this.zmjg;
	}

	public void setZmjg(Integer zmjg) {
		this.zmjg = zmjg;
	}

	@Column(name = "HSBG")
	public Integer getHsbg() {
		return this.hsbg;
	}

	public void setHsbg(Integer hsbg) {
		this.hsbg = hsbg;
	}

	@Column(name = "ZhuanZhi")
	public Integer getZhuanZhi() {
		return this.zhuanZhi;
	}

	public void setZhuanZhi(Integer zhuanZhi) {
		this.zhuanZhi = zhuanZhi;
	}

	@Column(name = "JianZhi")
	public Integer getJianZhi() {
		return this.jianZhi;
	}

	public void setJianZhi(Integer jianZhi) {
		this.jianZhi = jianZhi;
	}

	@Column(name = "RYZS")
	public Integer getRyzs() {
		return this.ryzs;
	}

	public void setRyzs(Integer ryzs) {
		this.ryzs = ryzs;
	}

	@Column(name = "ZhanBi", length = 10)
	public String getZhanBi() {
		return this.zhanBi;
	}

	public void setZhanBi(String zhanBi) {
		this.zhanBi = zhanBi;
	}

	@Column(name = "RYDRS")
	public Integer getRydrs() {
		return this.rydrs;
	}

	public void setRydrs(Integer rydrs) {
		this.rydrs = rydrs;
	}

	@Column(name = "RYDCS")
	public Integer getRydcs() {
		return this.rydcs;
	}

	public void setRydcs(Integer rydcs) {
		this.rydcs = rydcs;
	}

	@Column(name = "BoShi")
	public Integer getBoShi() {
		return this.boShi;
	}

	public void setBoShi(Integer boShi) {
		this.boShi = boShi;
	}

	@Column(name = "ShuoShi")
	public Integer getShuoShi() {
		return this.shuoShi;
	}

	public void setShuoShi(Integer shuoShi) {
		this.shuoShi = shuoShi;
	}

	@Column(name = "BenKe")
	public Integer getBenKe() {
		return this.benKe;
	}

	public void setBenKe(Integer benKe) {
		this.benKe = benKe;
	}

	@Column(name = "QiTa")
	public Integer getQiTa() {
		return this.qiTa;
	}

	public void setQiTa(Integer qiTa) {
		this.qiTa = qiTa;
	}

	@Column(name = "PJNL")
	public Integer getPjnl() {
		return this.pjnl;
	}

	public void setPjnl(Integer pjnl) {
		this.pjnl = pjnl;
	}

	@Column(name = "YiXia")
	public Integer getYiXia() {
		return this.yiXia;
	}

	public void setYiXia(Integer yiXia) {
		this.yiXia = yiXia;
	}

	@Column(name = "YiShang")
	public Integer getYiShang() {
		return this.yiShang;
	}

	public void setYiShang(Integer yiShang) {
		this.yiShang = yiShang;
	}

	@Column(name = "GJZC")
	public Integer getGjzc() {
		return this.gjzc;
	}

	public void setGjzc(Integer gjzc) {
		this.gjzc = gjzc;
	}

	@Column(name = "ZJZC")
	public Integer getZjzc() {
		return this.zjzc;
	}

	public void setZjzc(Integer zjzc) {
		this.zjzc = zjzc;
	}

	@Column(name = "CJZC")
	public Integer getCjzc() {
		return this.cjzc;
	}

	public void setCjzc(Integer cjzc) {
		this.cjzc = cjzc;
	}

	@Column(name = "CIA")
	public Integer getCia() {
		return this.cia;
	}

	public void setCia(Integer cia) {
		this.cia = cia;
	}

	@Column(name = "CPA")
	public Integer getCpa() {
		return this.cpa;
	}

	public void setCpa(Integer cpa) {
		this.cpa = cpa;
	}

	@Column(name = "QTZG")
	public Integer getQtzg() {
		return this.qtzg;
	}

	public void setQtzg(Integer qtzg) {
		this.qtzg = qtzg;
	}

	@Column(name = "FZJGS2")
	public Integer getFzjgs2() {
		return this.fzjgs2;
	}

	public void setFzjgs2(Integer fzjgs2) {
		this.fzjgs2 = fzjgs2;
	}

	@Column(name = "ZMJG2")
	public Integer getZmjg2() {
		return this.zmjg2;
	}

	public void setZmjg2(Integer zmjg2) {
		this.zmjg2 = zmjg2;
	}

	@Column(name = "HSBG2")
	public Integer getHsbg2() {
		return this.hsbg2;
	}

	public void setHsbg2(Integer hsbg2) {
		this.hsbg2 = hsbg2;
	}

	@Column(name = "ZhuanZhi2")
	public Integer getZhuanZhi2() {
		return this.zhuanZhi2;
	}

	public void setZhuanZhi2(Integer zhuanZhi2) {
		this.zhuanZhi2 = zhuanZhi2;
	}

	@Column(name = "JianZhi2")
	public Integer getJianZhi2() {
		return this.jianZhi2;
	}

	public void setJianZhi2(Integer jianZhi2) {
		this.jianZhi2 = jianZhi2;
	}

	@Column(name = "RYZS2")
	public Integer getRyzs2() {
		return this.ryzs2;
	}

	public void setRyzs2(Integer ryzs2) {
		this.ryzs2 = ryzs2;
	}

	@Column(name = "ZhanBi2", length = 10)
	public String getZhanBi2() {
		return this.zhanBi2;
	}

	public void setZhanBi2(String zhanBi2) {
		this.zhanBi2 = zhanBi2;
	}

	@Column(name = "RYDRS2")
	public Integer getRydrs2() {
		return this.rydrs2;
	}

	public void setRydrs2(Integer rydrs2) {
		this.rydrs2 = rydrs2;
	}

	@Column(name = "RYDCS2")
	public Integer getRydcs2() {
		return this.rydcs2;
	}

	public void setRydcs2(Integer rydcs2) {
		this.rydcs2 = rydcs2;
	}

	@Column(name = "BoShi2")
	public Integer getBoShi2() {
		return this.boShi2;
	}

	public void setBoShi2(Integer boShi2) {
		this.boShi2 = boShi2;
	}

	@Column(name = "ShuoShi2")
	public Integer getShuoShi2() {
		return this.shuoShi2;
	}

	public void setShuoShi2(Integer shuoShi2) {
		this.shuoShi2 = shuoShi2;
	}

	@Column(name = "BenKe2")
	public Integer getBenKe2() {
		return this.benKe2;
	}

	public void setBenKe2(Integer benKe2) {
		this.benKe2 = benKe2;
	}

	@Column(name = "QiTa2")
	public Integer getQiTa2() {
		return this.qiTa2;
	}

	public void setQiTa2(Integer qiTa2) {
		this.qiTa2 = qiTa2;
	}

	@Column(name = "PJNL2")
	public Integer getPjnl2() {
		return this.pjnl2;
	}

	public void setPjnl2(Integer pjnl2) {
		this.pjnl2 = pjnl2;
	}

	@Column(name = "YiXia2")
	public Integer getYiXia2() {
		return this.yiXia2;
	}

	public void setYiXia2(Integer yiXia2) {
		this.yiXia2 = yiXia2;
	}

	@Column(name = "YiShang2")
	public Integer getYiShang2() {
		return this.yiShang2;
	}

	public void setYiShang2(Integer yiShang2) {
		this.yiShang2 = yiShang2;
	}

	@Column(name = "GJZC2")
	public Integer getGjzc2() {
		return this.gjzc2;
	}

	public void setGjzc2(Integer gjzc2) {
		this.gjzc2 = gjzc2;
	}

	@Column(name = "ZJZC2")
	public Integer getZjzc2() {
		return this.zjzc2;
	}

	public void setZjzc2(Integer zjzc2) {
		this.zjzc2 = zjzc2;
	}

	@Column(name = "CJZC2")
	public Integer getCjzc2() {
		return this.cjzc2;
	}

	public void setCjzc2(Integer cjzc2) {
		this.cjzc2 = cjzc2;
	}

	@Column(name = "CIA2")
	public Integer getCia2() {
		return this.cia2;
	}

	public void setCia2(Integer cia2) {
		this.cia2 = cia2;
	}

	@Column(name = "CPA2")
	public Integer getCpa2() {
		return this.cpa2;
	}

	public void setCpa2(Integer cpa2) {
		this.cpa2 = cpa2;
	}

	@Column(name = "QTZG2")
	public Integer getQtzg2() {
		return this.qtzg2;
	}

	public void setQtzg2(Integer qtzg2) {
		this.qtzg2 = qtzg2;
	}

	@Column(name = "FZJGS3")
	public Integer getFzjgs3() {
		return this.fzjgs3;
	}

	public void setFzjgs3(Integer fzjgs3) {
		this.fzjgs3 = fzjgs3;
	}

	@Column(name = "ZMJG3")
	public Integer getZmjg3() {
		return this.zmjg3;
	}

	public void setZmjg3(Integer zmjg3) {
		this.zmjg3 = zmjg3;
	}

	@Column(name = "HSBG3")
	public Integer getHsbg3() {
		return this.hsbg3;
	}

	public void setHsbg3(Integer hsbg3) {
		this.hsbg3 = hsbg3;
	}

	@Column(name = "ZhuanZhi3")
	public Integer getZhuanZhi3() {
		return this.zhuanZhi3;
	}

	public void setZhuanZhi3(Integer zhuanZhi3) {
		this.zhuanZhi3 = zhuanZhi3;
	}

	@Column(name = "JianZhi3")
	public Integer getJianZhi3() {
		return this.jianZhi3;
	}

	public void setJianZhi3(Integer jianZhi3) {
		this.jianZhi3 = jianZhi3;
	}

	@Column(name = "RYZS3")
	public Integer getRyzs3() {
		return this.ryzs3;
	}

	public void setRyzs3(Integer ryzs3) {
		this.ryzs3 = ryzs3;
	}

	@Column(name = "ZhanBi3", length = 10)
	public String getZhanBi3() {
		return this.zhanBi3;
	}

	public void setZhanBi3(String zhanBi3) {
		this.zhanBi3 = zhanBi3;
	}

	@Column(name = "RYDRS3")
	public Integer getRydrs3() {
		return this.rydrs3;
	}

	public void setRydrs3(Integer rydrs3) {
		this.rydrs3 = rydrs3;
	}

	@Column(name = "RYDCS3")
	public Integer getRydcs3() {
		return this.rydcs3;
	}

	public void setRydcs3(Integer rydcs3) {
		this.rydcs3 = rydcs3;
	}

	@Column(name = "BoShi3")
	public Integer getBoShi3() {
		return this.boShi3;
	}

	public void setBoShi3(Integer boShi3) {
		this.boShi3 = boShi3;
	}

	@Column(name = "ShuoShi3")
	public Integer getShuoShi3() {
		return this.shuoShi3;
	}

	public void setShuoShi3(Integer shuoShi3) {
		this.shuoShi3 = shuoShi3;
	}

	@Column(name = "BenKe3")
	public Integer getBenKe3() {
		return this.benKe3;
	}

	public void setBenKe3(Integer benKe3) {
		this.benKe3 = benKe3;
	}

	@Column(name = "QiTa3")
	public Integer getQiTa3() {
		return this.qiTa3;
	}

	public void setQiTa3(Integer qiTa3) {
		this.qiTa3 = qiTa3;
	}

	@Column(name = "PJNL3")
	public Integer getPjnl3() {
		return this.pjnl3;
	}

	public void setPjnl3(Integer pjnl3) {
		this.pjnl3 = pjnl3;
	}

	@Column(name = "YiXia3")
	public Integer getYiXia3() {
		return this.yiXia3;
	}

	public void setYiXia3(Integer yiXia3) {
		this.yiXia3 = yiXia3;
	}

	@Column(name = "YiShang3")
	public Integer getYiShang3() {
		return this.yiShang3;
	}

	public void setYiShang3(Integer yiShang3) {
		this.yiShang3 = yiShang3;
	}

	@Column(name = "GJZC3")
	public Integer getGjzc3() {
		return this.gjzc3;
	}

	public void setGjzc3(Integer gjzc3) {
		this.gjzc3 = gjzc3;
	}

	@Column(name = "ZJZC3")
	public Integer getZjzc3() {
		return this.zjzc3;
	}

	public void setZjzc3(Integer zjzc3) {
		this.zjzc3 = zjzc3;
	}

	@Column(name = "CJZC3")
	public Integer getCjzc3() {
		return this.cjzc3;
	}

	public void setCjzc3(Integer cjzc3) {
		this.cjzc3 = cjzc3;
	}

	@Column(name = "CIA3")
	public Integer getCia3() {
		return this.cia3;
	}

	public void setCia3(Integer cia3) {
		this.cia3 = cia3;
	}

	@Column(name = "CPA3")
	public Integer getCpa3() {
		return this.cpa3;
	}

	public void setCpa3(Integer cpa3) {
		this.cpa3 = cpa3;
	}

	@Column(name = "QTZG3")
	public Integer getQtzg3() {
		return this.qtzg3;
	}

	public void setQtzg3(Integer qtzg3) {
		this.qtzg3 = qtzg3;
	}

	@Column(name = "FZJGS4")
	public Integer getFzjgs4() {
		return this.fzjgs4;
	}

	public void setFzjgs4(Integer fzjgs4) {
		this.fzjgs4 = fzjgs4;
	}

	@Column(name = "ZMJG4")
	public Integer getZmjg4() {
		return this.zmjg4;
	}

	public void setZmjg4(Integer zmjg4) {
		this.zmjg4 = zmjg4;
	}

	@Column(name = "HSBG4")
	public Integer getHsbg4() {
		return this.hsbg4;
	}

	public void setHsbg4(Integer hsbg4) {
		this.hsbg4 = hsbg4;
	}

	@Column(name = "ZhuanZhi4")
	public Integer getZhuanZhi4() {
		return this.zhuanZhi4;
	}

	public void setZhuanZhi4(Integer zhuanZhi4) {
		this.zhuanZhi4 = zhuanZhi4;
	}

	@Column(name = "JianZhi4")
	public Integer getJianZhi4() {
		return this.jianZhi4;
	}

	public void setJianZhi4(Integer jianZhi4) {
		this.jianZhi4 = jianZhi4;
	}

	@Column(name = "RYZS4")
	public Integer getRyzs4() {
		return this.ryzs4;
	}

	public void setRyzs4(Integer ryzs4) {
		this.ryzs4 = ryzs4;
	}

	@Column(name = "ZhanBi4", length = 10)
	public String getZhanBi4() {
		return this.zhanBi4;
	}

	public void setZhanBi4(String zhanBi4) {
		this.zhanBi4 = zhanBi4;
	}

	@Column(name = "RYDRS4")
	public Integer getRydrs4() {
		return this.rydrs4;
	}

	public void setRydrs4(Integer rydrs4) {
		this.rydrs4 = rydrs4;
	}

	@Column(name = "RYDCS4")
	public Integer getRydcs4() {
		return this.rydcs4;
	}

	public void setRydcs4(Integer rydcs4) {
		this.rydcs4 = rydcs4;
	}

	@Column(name = "BoShi4")
	public Integer getBoShi4() {
		return this.boShi4;
	}

	public void setBoShi4(Integer boShi4) {
		this.boShi4 = boShi4;
	}

	@Column(name = "ShuoShi4")
	public Integer getShuoShi4() {
		return this.shuoShi4;
	}

	public void setShuoShi4(Integer shuoShi4) {
		this.shuoShi4 = shuoShi4;
	}

	@Column(name = "BenKe4")
	public Integer getBenKe4() {
		return this.benKe4;
	}

	public void setBenKe4(Integer benKe4) {
		this.benKe4 = benKe4;
	}

	@Column(name = "QiTa4")
	public Integer getQiTa4() {
		return this.qiTa4;
	}

	public void setQiTa4(Integer qiTa4) {
		this.qiTa4 = qiTa4;
	}

	@Column(name = "PJNL4")
	public Integer getPjnl4() {
		return this.pjnl4;
	}

	public void setPjnl4(Integer pjnl4) {
		this.pjnl4 = pjnl4;
	}

	@Column(name = "YiXia4")
	public Integer getYiXia4() {
		return this.yiXia4;
	}

	public void setYiXia4(Integer yiXia4) {
		this.yiXia4 = yiXia4;
	}

	@Column(name = "YiShang4")
	public Integer getYiShang4() {
		return this.yiShang4;
	}

	public void setYiShang4(Integer yiShang4) {
		this.yiShang4 = yiShang4;
	}

	@Column(name = "GJZC4")
	public Integer getGjzc4() {
		return this.gjzc4;
	}

	public void setGjzc4(Integer gjzc4) {
		this.gjzc4 = gjzc4;
	}

	@Column(name = "ZJZC4")
	public Integer getZjzc4() {
		return this.zjzc4;
	}

	public void setZjzc4(Integer zjzc4) {
		this.zjzc4 = zjzc4;
	}

	@Column(name = "CJZC4")
	public Integer getCjzc4() {
		return this.cjzc4;
	}

	public void setCjzc4(Integer cjzc4) {
		this.cjzc4 = cjzc4;
	}

	@Column(name = "CIA4")
	public Integer getCia4() {
		return this.cia4;
	}

	public void setCia4(Integer cia4) {
		this.cia4 = cia4;
	}

	@Column(name = "CPA4")
	public Integer getCpa4() {
		return this.cpa4;
	}

	public void setCpa4(Integer cpa4) {
		this.cpa4 = cpa4;
	}

	@Column(name = "QTZG4")
	public Integer getQtzg4() {
		return this.qtzg4;
	}

	public void setQtzg4(Integer qtzg4) {
		this.qtzg4 = qtzg4;
	}

	@Column(name = "BKZB", length = 12)
	public String getBkzb() {
		return this.bkzb;
	}

	public void setBkzb(String bkzb) {
		this.bkzb = bkzb;
	}

	@Column(name = "BKZB2", length = 12)
	public String getBkzb2() {
		return this.bkzb2;
	}

	public void setBkzb2(String bkzb2) {
		this.bkzb2 = bkzb2;
	}

	@Column(name = "BKZB3", length = 12)
	public String getBkzb3() {
		return this.bkzb3;
	}

	public void setBkzb3(String bkzb3) {
		this.bkzb3 = bkzb3;
	}

	@Column(name = "BKZB4", length = 12)
	public String getBkzb4() {
		return this.bkzb4;
	}

	public void setBkzb4(String bkzb4) {
		this.bkzb4 = bkzb4;
	}

}
