package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Foundproblem generated by hbm2java
 */
@Entity
@Table(name = "foundproblem", catalog = "audit", uniqueConstraints = @UniqueConstraint(columnNames = "year"))
public class FoundProblem implements java.io.Serializable {

	private Integer id;
	private int year;
	private int state;
	private String sumbitOne;
	private String sumbitDate;
	private String name;
	private int editDpt;
	private Integer td1;
	private Integer td2;
	private Integer td3;
	private Integer td4;
	private Integer td5;
	private Integer td6;
	private Integer td7;
	private Integer td8;
	private Integer td9;
	private Integer td10;
	private Integer td11;
	private Integer td12;
	private Integer td13;
	private Integer td14;
	private Integer td15;
	private Integer td16;
	private Integer td17;
	private Integer td18;
	private Integer td19;
	private Integer td20;
	private Integer td21;
	private Integer td22;
	private Integer td23;
	private Integer td24;
	private Integer td25;
	private Integer td26;
	private Integer td27;
	private Integer td28;
	private Integer td29;
	private Integer td30;
	private Integer td31;
	private Integer td32;
	private Integer td33;
	private Integer td34;
	private Integer td35;
	private Integer td36;
	private Integer td37;
	private Integer td38;
	private Integer td39;
	private Integer td40;
	private Integer td41;
	private Integer td42;
	private Integer td43;
	private Integer td44;
	private Integer td45;
	private Integer td46;
	private Integer td47;
	private Integer td48;
	private Integer td49;
	private Integer td50;
	private Integer td51;
	private Integer td52;
	private Integer td53;
	private Integer td54;
	private Integer td55;
	private Integer td56;
	private Integer td57;
	private Integer td58;
	private Integer td59;
	private Integer td60;
	private Integer td61;
	private Integer td62;
	private Integer td63;
	private Integer td64;
	private Integer td65;
	private Integer td66;
	private Integer td67;
	private Integer td68;
	private Integer td69;
	private Integer td70;
	private Integer td71;
	private Integer td72;
	private Integer td73;
	private Integer td74;
	private Integer td75;
	private Integer td76;
	private Integer td77;
	private Integer td78;
	private Integer td79;
	private Integer td80;
	private Integer td81;
	private Integer td82;
	private Integer td83;
	private Integer td84;
	private Integer td85;
	private Integer td86;
	private Integer td87;
	private Integer td88;
	private Integer td89;
	private Integer td90;
	private Integer td91;
	private Integer td92;
	private Integer td93;
	private Integer td94;
	private Integer td95;
	private Integer td96;
	private Integer td97;
	private Integer td98;
	private Integer td99;
	private Integer td100;
	private Integer td101;
	private Integer td102;
	private Integer td103;
	private Integer td104;
	private Integer td105;
	private Integer td106;
	private Integer td107;
	private Integer td108;
	private Integer td109;
	private Integer td110;
	private Integer td111;
	private Integer td112;
	private Integer td113;
	private Integer td114;
	private Integer td115;
	private Integer td116;
	private Integer td117;
	private Integer td118;
	private Integer td119;
	private Integer td120;
	private Integer td121;
	private Integer td122;
	private Integer td123;
	private Integer td124;
	private Integer td125;
	private Integer td126;
	private Integer td127;
	private Integer td128;
	private Integer td129;
	private Integer td130;
	private Integer td131;
	private Integer td132;

	public FoundProblem() {
	}

	public FoundProblem(int year, int state, String sumbitOne, String name, int editDpt) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.name = name;
		this.editDpt = editDpt;
	}

	public FoundProblem(int year, int state, String sumbitOne, String sumbitDate, String name, int editDpt, Integer td1,
			Integer td2, Integer td3, Integer td4, Integer td5, Integer td6, Integer td7, Integer td8, Integer td9,
			Integer td10, Integer td11, Integer td12, Integer td13, Integer td14, Integer td15, Integer td16,
			Integer td17, Integer td18, Integer td19, Integer td20, Integer td21, Integer td22, Integer td23,
			Integer td24, Integer td25, Integer td26, Integer td27, Integer td28, Integer td29, Integer td30,
			Integer td31, Integer td32, Integer td33, Integer td34, Integer td35, Integer td36, Integer td37,
			Integer td38, Integer td39, Integer td40, Integer td41, Integer td42, Integer td43, Integer td44,
			Integer td45, Integer td46, Integer td47, Integer td48, Integer td49, Integer td50, Integer td51,
			Integer td52, Integer td53, Integer td54, Integer td55, Integer td56, Integer td57, Integer td58,
			Integer td59, Integer td60, Integer td61, Integer td62, Integer td63, Integer td64, Integer td65,
			Integer td66, Integer td67, Integer td68, Integer td69, Integer td70, Integer td71, Integer td72,
			Integer td73, Integer td74, Integer td75, Integer td76, Integer td77, Integer td78, Integer td79,
			Integer td80, Integer td81, Integer td82, Integer td83, Integer td84, Integer td85, Integer td86,
			Integer td87, Integer td88, Integer td89, Integer td90, Integer td91, Integer td92, Integer td93,
			Integer td94, Integer td95, Integer td96, Integer td97, Integer td98, Integer td99, Integer td100,
			Integer td101, Integer td102, Integer td103, Integer td104, Integer td105, Integer td106, Integer td107,
			Integer td108, Integer td109, Integer td110, Integer td111, Integer td112, Integer td113, Integer td114,
			Integer td115, Integer td116, Integer td117, Integer td118, Integer td119, Integer td120, Integer td121,
			Integer td122, Integer td123, Integer td124, Integer td125, Integer td126, Integer td127, Integer td128,
			Integer td129, Integer td130, Integer td131, Integer td132) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.sumbitDate = sumbitDate;
		this.name = name;
		this.editDpt = editDpt;
		this.td1 = td1;
		this.td2 = td2;
		this.td3 = td3;
		this.td4 = td4;
		this.td5 = td5;
		this.td6 = td6;
		this.td7 = td7;
		this.td8 = td8;
		this.td9 = td9;
		this.td10 = td10;
		this.td11 = td11;
		this.td12 = td12;
		this.td13 = td13;
		this.td14 = td14;
		this.td15 = td15;
		this.td16 = td16;
		this.td17 = td17;
		this.td18 = td18;
		this.td19 = td19;
		this.td20 = td20;
		this.td21 = td21;
		this.td22 = td22;
		this.td23 = td23;
		this.td24 = td24;
		this.td25 = td25;
		this.td26 = td26;
		this.td27 = td27;
		this.td28 = td28;
		this.td29 = td29;
		this.td30 = td30;
		this.td31 = td31;
		this.td32 = td32;
		this.td33 = td33;
		this.td34 = td34;
		this.td35 = td35;
		this.td36 = td36;
		this.td37 = td37;
		this.td38 = td38;
		this.td39 = td39;
		this.td40 = td40;
		this.td41 = td41;
		this.td42 = td42;
		this.td43 = td43;
		this.td44 = td44;
		this.td45 = td45;
		this.td46 = td46;
		this.td47 = td47;
		this.td48 = td48;
		this.td49 = td49;
		this.td50 = td50;
		this.td51 = td51;
		this.td52 = td52;
		this.td53 = td53;
		this.td54 = td54;
		this.td55 = td55;
		this.td56 = td56;
		this.td57 = td57;
		this.td58 = td58;
		this.td59 = td59;
		this.td60 = td60;
		this.td61 = td61;
		this.td62 = td62;
		this.td63 = td63;
		this.td64 = td64;
		this.td65 = td65;
		this.td66 = td66;
		this.td67 = td67;
		this.td68 = td68;
		this.td69 = td69;
		this.td70 = td70;
		this.td71 = td71;
		this.td72 = td72;
		this.td73 = td73;
		this.td74 = td74;
		this.td75 = td75;
		this.td76 = td76;
		this.td77 = td77;
		this.td78 = td78;
		this.td79 = td79;
		this.td80 = td80;
		this.td81 = td81;
		this.td82 = td82;
		this.td83 = td83;
		this.td84 = td84;
		this.td85 = td85;
		this.td86 = td86;
		this.td87 = td87;
		this.td88 = td88;
		this.td89 = td89;
		this.td90 = td90;
		this.td91 = td91;
		this.td92 = td92;
		this.td93 = td93;
		this.td94 = td94;
		this.td95 = td95;
		this.td96 = td96;
		this.td97 = td97;
		this.td98 = td98;
		this.td99 = td99;
		this.td100 = td100;
		this.td101 = td101;
		this.td102 = td102;
		this.td103 = td103;
		this.td104 = td104;
		this.td105 = td105;
		this.td106 = td106;
		this.td107 = td107;
		this.td108 = td108;
		this.td109 = td109;
		this.td110 = td110;
		this.td111 = td111;
		this.td112 = td112;
		this.td113 = td113;
		this.td114 = td114;
		this.td115 = td115;
		this.td116 = td116;
		this.td117 = td117;
		this.td118 = td118;
		this.td119 = td119;
		this.td120 = td120;
		this.td121 = td121;
		this.td122 = td122;
		this.td123 = td123;
		this.td124 = td124;
		this.td125 = td125;
		this.td126 = td126;
		this.td127 = td127;
		this.td128 = td128;
		this.td129 = td129;
		this.td130 = td130;
		this.td131 = td131;
		this.td132 = td132;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year", unique = true, nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "sumbitOne", nullable = false, length = 12)
	public String getSumbitOne() {
		return this.sumbitOne;
	}

	public void setSumbitOne(String sumbitOne) {
		this.sumbitOne = sumbitOne;
	}

	@Column(name = "sumbitDate", length = 32)
	public String getSumbitDate() {
		return this.sumbitDate;
	}

	public void setSumbitDate(String sumbitDate) {
		this.sumbitDate = sumbitDate;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "editDpt", nullable = false)
	public int getEditDpt() {
		return this.editDpt;
	}

	public void setEditDpt(int editDpt) {
		this.editDpt = editDpt;
	}

	@Column(name = "td1")
	public Integer getTd1() {
		return this.td1;
	}

	public void setTd1(Integer td1) {
		this.td1 = td1;
	}

	@Column(name = "td2")
	public Integer getTd2() {
		return this.td2;
	}

	public void setTd2(Integer td2) {
		this.td2 = td2;
	}

	@Column(name = "td3")
	public Integer getTd3() {
		return this.td3;
	}

	public void setTd3(Integer td3) {
		this.td3 = td3;
	}

	@Column(name = "td4")
	public Integer getTd4() {
		return this.td4;
	}

	public void setTd4(Integer td4) {
		this.td4 = td4;
	}

	@Column(name = "td5")
	public Integer getTd5() {
		return this.td5;
	}

	public void setTd5(Integer td5) {
		this.td5 = td5;
	}

	@Column(name = "td6")
	public Integer getTd6() {
		return this.td6;
	}

	public void setTd6(Integer td6) {
		this.td6 = td6;
	}

	@Column(name = "td7")
	public Integer getTd7() {
		return this.td7;
	}

	public void setTd7(Integer td7) {
		this.td7 = td7;
	}

	@Column(name = "td8")
	public Integer getTd8() {
		return this.td8;
	}

	public void setTd8(Integer td8) {
		this.td8 = td8;
	}

	@Column(name = "td9")
	public Integer getTd9() {
		return this.td9;
	}

	public void setTd9(Integer td9) {
		this.td9 = td9;
	}

	@Column(name = "td10")
	public Integer getTd10() {
		return this.td10;
	}

	public void setTd10(Integer td10) {
		this.td10 = td10;
	}

	@Column(name = "td11")
	public Integer getTd11() {
		return this.td11;
	}

	public void setTd11(Integer td11) {
		this.td11 = td11;
	}

	@Column(name = "td12")
	public Integer getTd12() {
		return this.td12;
	}

	public void setTd12(Integer td12) {
		this.td12 = td12;
	}

	@Column(name = "td13")
	public Integer getTd13() {
		return this.td13;
	}

	public void setTd13(Integer td13) {
		this.td13 = td13;
	}

	@Column(name = "td14")
	public Integer getTd14() {
		return this.td14;
	}

	public void setTd14(Integer td14) {
		this.td14 = td14;
	}

	@Column(name = "td15")
	public Integer getTd15() {
		return this.td15;
	}

	public void setTd15(Integer td15) {
		this.td15 = td15;
	}

	@Column(name = "td16")
	public Integer getTd16() {
		return this.td16;
	}

	public void setTd16(Integer td16) {
		this.td16 = td16;
	}

	@Column(name = "td17")
	public Integer getTd17() {
		return this.td17;
	}

	public void setTd17(Integer td17) {
		this.td17 = td17;
	}

	@Column(name = "td18")
	public Integer getTd18() {
		return this.td18;
	}

	public void setTd18(Integer td18) {
		this.td18 = td18;
	}

	@Column(name = "td19")
	public Integer getTd19() {
		return this.td19;
	}

	public void setTd19(Integer td19) {
		this.td19 = td19;
	}

	@Column(name = "td20")
	public Integer getTd20() {
		return this.td20;
	}

	public void setTd20(Integer td20) {
		this.td20 = td20;
	}

	@Column(name = "td21")
	public Integer getTd21() {
		return this.td21;
	}

	public void setTd21(Integer td21) {
		this.td21 = td21;
	}

	@Column(name = "td22")
	public Integer getTd22() {
		return this.td22;
	}

	public void setTd22(Integer td22) {
		this.td22 = td22;
	}

	@Column(name = "td23")
	public Integer getTd23() {
		return this.td23;
	}

	public void setTd23(Integer td23) {
		this.td23 = td23;
	}

	@Column(name = "td24")
	public Integer getTd24() {
		return this.td24;
	}

	public void setTd24(Integer td24) {
		this.td24 = td24;
	}

	@Column(name = "td25")
	public Integer getTd25() {
		return this.td25;
	}

	public void setTd25(Integer td25) {
		this.td25 = td25;
	}

	@Column(name = "td26")
	public Integer getTd26() {
		return this.td26;
	}

	public void setTd26(Integer td26) {
		this.td26 = td26;
	}

	@Column(name = "td27")
	public Integer getTd27() {
		return this.td27;
	}

	public void setTd27(Integer td27) {
		this.td27 = td27;
	}

	@Column(name = "td28")
	public Integer getTd28() {
		return this.td28;
	}

	public void setTd28(Integer td28) {
		this.td28 = td28;
	}

	@Column(name = "td29")
	public Integer getTd29() {
		return this.td29;
	}

	public void setTd29(Integer td29) {
		this.td29 = td29;
	}

	@Column(name = "td30")
	public Integer getTd30() {
		return this.td30;
	}

	public void setTd30(Integer td30) {
		this.td30 = td30;
	}

	@Column(name = "td31")
	public Integer getTd31() {
		return this.td31;
	}

	public void setTd31(Integer td31) {
		this.td31 = td31;
	}

	@Column(name = "td32")
	public Integer getTd32() {
		return this.td32;
	}

	public void setTd32(Integer td32) {
		this.td32 = td32;
	}

	@Column(name = "td33")
	public Integer getTd33() {
		return this.td33;
	}

	public void setTd33(Integer td33) {
		this.td33 = td33;
	}

	@Column(name = "td34")
	public Integer getTd34() {
		return this.td34;
	}

	public void setTd34(Integer td34) {
		this.td34 = td34;
	}

	@Column(name = "td35")
	public Integer getTd35() {
		return this.td35;
	}

	public void setTd35(Integer td35) {
		this.td35 = td35;
	}

	@Column(name = "td36")
	public Integer getTd36() {
		return this.td36;
	}

	public void setTd36(Integer td36) {
		this.td36 = td36;
	}

	@Column(name = "td37")
	public Integer getTd37() {
		return this.td37;
	}

	public void setTd37(Integer td37) {
		this.td37 = td37;
	}

	@Column(name = "td38")
	public Integer getTd38() {
		return this.td38;
	}

	public void setTd38(Integer td38) {
		this.td38 = td38;
	}

	@Column(name = "td39")
	public Integer getTd39() {
		return this.td39;
	}

	public void setTd39(Integer td39) {
		this.td39 = td39;
	}

	@Column(name = "td40")
	public Integer getTd40() {
		return this.td40;
	}

	public void setTd40(Integer td40) {
		this.td40 = td40;
	}

	@Column(name = "td41")
	public Integer getTd41() {
		return this.td41;
	}

	public void setTd41(Integer td41) {
		this.td41 = td41;
	}

	@Column(name = "td42")
	public Integer getTd42() {
		return this.td42;
	}

	public void setTd42(Integer td42) {
		this.td42 = td42;
	}

	@Column(name = "td43")
	public Integer getTd43() {
		return this.td43;
	}

	public void setTd43(Integer td43) {
		this.td43 = td43;
	}

	@Column(name = "td44")
	public Integer getTd44() {
		return this.td44;
	}

	public void setTd44(Integer td44) {
		this.td44 = td44;
	}

	@Column(name = "td45")
	public Integer getTd45() {
		return this.td45;
	}

	public void setTd45(Integer td45) {
		this.td45 = td45;
	}

	@Column(name = "td46")
	public Integer getTd46() {
		return this.td46;
	}

	public void setTd46(Integer td46) {
		this.td46 = td46;
	}

	@Column(name = "td47")
	public Integer getTd47() {
		return this.td47;
	}

	public void setTd47(Integer td47) {
		this.td47 = td47;
	}

	@Column(name = "td48")
	public Integer getTd48() {
		return this.td48;
	}

	public void setTd48(Integer td48) {
		this.td48 = td48;
	}

	@Column(name = "td49")
	public Integer getTd49() {
		return this.td49;
	}

	public void setTd49(Integer td49) {
		this.td49 = td49;
	}

	@Column(name = "td50")
	public Integer getTd50() {
		return this.td50;
	}

	public void setTd50(Integer td50) {
		this.td50 = td50;
	}

	@Column(name = "td51")
	public Integer getTd51() {
		return this.td51;
	}

	public void setTd51(Integer td51) {
		this.td51 = td51;
	}

	@Column(name = "td52")
	public Integer getTd52() {
		return this.td52;
	}

	public void setTd52(Integer td52) {
		this.td52 = td52;
	}

	@Column(name = "td53")
	public Integer getTd53() {
		return this.td53;
	}

	public void setTd53(Integer td53) {
		this.td53 = td53;
	}

	@Column(name = "td54")
	public Integer getTd54() {
		return this.td54;
	}

	public void setTd54(Integer td54) {
		this.td54 = td54;
	}

	@Column(name = "td55")
	public Integer getTd55() {
		return this.td55;
	}

	public void setTd55(Integer td55) {
		this.td55 = td55;
	}

	@Column(name = "td56")
	public Integer getTd56() {
		return this.td56;
	}

	public void setTd56(Integer td56) {
		this.td56 = td56;
	}

	@Column(name = "td57")
	public Integer getTd57() {
		return this.td57;
	}

	public void setTd57(Integer td57) {
		this.td57 = td57;
	}

	@Column(name = "td58")
	public Integer getTd58() {
		return this.td58;
	}

	public void setTd58(Integer td58) {
		this.td58 = td58;
	}

	@Column(name = "td59")
	public Integer getTd59() {
		return this.td59;
	}

	public void setTd59(Integer td59) {
		this.td59 = td59;
	}

	@Column(name = "td60")
	public Integer getTd60() {
		return this.td60;
	}

	public void setTd60(Integer td60) {
		this.td60 = td60;
	}

	@Column(name = "td61")
	public Integer getTd61() {
		return this.td61;
	}

	public void setTd61(Integer td61) {
		this.td61 = td61;
	}

	@Column(name = "td62")
	public Integer getTd62() {
		return this.td62;
	}

	public void setTd62(Integer td62) {
		this.td62 = td62;
	}

	@Column(name = "td63")
	public Integer getTd63() {
		return this.td63;
	}

	public void setTd63(Integer td63) {
		this.td63 = td63;
	}

	@Column(name = "td64")
	public Integer getTd64() {
		return this.td64;
	}

	public void setTd64(Integer td64) {
		this.td64 = td64;
	}

	@Column(name = "td65")
	public Integer getTd65() {
		return this.td65;
	}

	public void setTd65(Integer td65) {
		this.td65 = td65;
	}

	@Column(name = "td66")
	public Integer getTd66() {
		return this.td66;
	}

	public void setTd66(Integer td66) {
		this.td66 = td66;
	}

	@Column(name = "td67")
	public Integer getTd67() {
		return this.td67;
	}

	public void setTd67(Integer td67) {
		this.td67 = td67;
	}

	@Column(name = "td68")
	public Integer getTd68() {
		return this.td68;
	}

	public void setTd68(Integer td68) {
		this.td68 = td68;
	}

	@Column(name = "td69")
	public Integer getTd69() {
		return this.td69;
	}

	public void setTd69(Integer td69) {
		this.td69 = td69;
	}

	@Column(name = "td70")
	public Integer getTd70() {
		return this.td70;
	}

	public void setTd70(Integer td70) {
		this.td70 = td70;
	}

	@Column(name = "td71")
	public Integer getTd71() {
		return this.td71;
	}

	public void setTd71(Integer td71) {
		this.td71 = td71;
	}

	@Column(name = "td72")
	public Integer getTd72() {
		return this.td72;
	}

	public void setTd72(Integer td72) {
		this.td72 = td72;
	}

	@Column(name = "td73")
	public Integer getTd73() {
		return this.td73;
	}

	public void setTd73(Integer td73) {
		this.td73 = td73;
	}

	@Column(name = "td74")
	public Integer getTd74() {
		return this.td74;
	}

	public void setTd74(Integer td74) {
		this.td74 = td74;
	}

	@Column(name = "td75")
	public Integer getTd75() {
		return this.td75;
	}

	public void setTd75(Integer td75) {
		this.td75 = td75;
	}

	@Column(name = "td76")
	public Integer getTd76() {
		return this.td76;
	}

	public void setTd76(Integer td76) {
		this.td76 = td76;
	}

	@Column(name = "td77")
	public Integer getTd77() {
		return this.td77;
	}

	public void setTd77(Integer td77) {
		this.td77 = td77;
	}

	@Column(name = "td78")
	public Integer getTd78() {
		return this.td78;
	}

	public void setTd78(Integer td78) {
		this.td78 = td78;
	}

	@Column(name = "td79")
	public Integer getTd79() {
		return this.td79;
	}

	public void setTd79(Integer td79) {
		this.td79 = td79;
	}

	@Column(name = "td80")
	public Integer getTd80() {
		return this.td80;
	}

	public void setTd80(Integer td80) {
		this.td80 = td80;
	}

	@Column(name = "td81")
	public Integer getTd81() {
		return this.td81;
	}

	public void setTd81(Integer td81) {
		this.td81 = td81;
	}

	@Column(name = "td82")
	public Integer getTd82() {
		return this.td82;
	}

	public void setTd82(Integer td82) {
		this.td82 = td82;
	}

	@Column(name = "td83")
	public Integer getTd83() {
		return this.td83;
	}

	public void setTd83(Integer td83) {
		this.td83 = td83;
	}

	@Column(name = "td84")
	public Integer getTd84() {
		return this.td84;
	}

	public void setTd84(Integer td84) {
		this.td84 = td84;
	}

	@Column(name = "td85")
	public Integer getTd85() {
		return this.td85;
	}

	public void setTd85(Integer td85) {
		this.td85 = td85;
	}

	@Column(name = "td86")
	public Integer getTd86() {
		return this.td86;
	}

	public void setTd86(Integer td86) {
		this.td86 = td86;
	}

	@Column(name = "td87")
	public Integer getTd87() {
		return this.td87;
	}

	public void setTd87(Integer td87) {
		this.td87 = td87;
	}

	@Column(name = "td88")
	public Integer getTd88() {
		return this.td88;
	}

	public void setTd88(Integer td88) {
		this.td88 = td88;
	}

	@Column(name = "td89")
	public Integer getTd89() {
		return this.td89;
	}

	public void setTd89(Integer td89) {
		this.td89 = td89;
	}

	@Column(name = "td90")
	public Integer getTd90() {
		return this.td90;
	}

	public void setTd90(Integer td90) {
		this.td90 = td90;
	}

	@Column(name = "td91")
	public Integer getTd91() {
		return this.td91;
	}

	public void setTd91(Integer td91) {
		this.td91 = td91;
	}

	@Column(name = "td92")
	public Integer getTd92() {
		return this.td92;
	}

	public void setTd92(Integer td92) {
		this.td92 = td92;
	}

	@Column(name = "td93")
	public Integer getTd93() {
		return this.td93;
	}

	public void setTd93(Integer td93) {
		this.td93 = td93;
	}

	@Column(name = "td94")
	public Integer getTd94() {
		return this.td94;
	}

	public void setTd94(Integer td94) {
		this.td94 = td94;
	}

	@Column(name = "td95")
	public Integer getTd95() {
		return this.td95;
	}

	public void setTd95(Integer td95) {
		this.td95 = td95;
	}

	@Column(name = "td96")
	public Integer getTd96() {
		return this.td96;
	}

	public void setTd96(Integer td96) {
		this.td96 = td96;
	}

	@Column(name = "td97")
	public Integer getTd97() {
		return this.td97;
	}

	public void setTd97(Integer td97) {
		this.td97 = td97;
	}

	@Column(name = "td98")
	public Integer getTd98() {
		return this.td98;
	}

	public void setTd98(Integer td98) {
		this.td98 = td98;
	}

	@Column(name = "td99")
	public Integer getTd99() {
		return this.td99;
	}

	public void setTd99(Integer td99) {
		this.td99 = td99;
	}

	@Column(name = "td100")
	public Integer getTd100() {
		return this.td100;
	}

	public void setTd100(Integer td100) {
		this.td100 = td100;
	}

	@Column(name = "td101")
	public Integer getTd101() {
		return this.td101;
	}

	public void setTd101(Integer td101) {
		this.td101 = td101;
	}

	@Column(name = "td102")
	public Integer getTd102() {
		return this.td102;
	}

	public void setTd102(Integer td102) {
		this.td102 = td102;
	}

	@Column(name = "td103")
	public Integer getTd103() {
		return this.td103;
	}

	public void setTd103(Integer td103) {
		this.td103 = td103;
	}

	@Column(name = "td104")
	public Integer getTd104() {
		return this.td104;
	}

	public void setTd104(Integer td104) {
		this.td104 = td104;
	}

	@Column(name = "td105")
	public Integer getTd105() {
		return this.td105;
	}

	public void setTd105(Integer td105) {
		this.td105 = td105;
	}

	@Column(name = "td106")
	public Integer getTd106() {
		return this.td106;
	}

	public void setTd106(Integer td106) {
		this.td106 = td106;
	}

	@Column(name = "td107")
	public Integer getTd107() {
		return this.td107;
	}

	public void setTd107(Integer td107) {
		this.td107 = td107;
	}

	@Column(name = "td108")
	public Integer getTd108() {
		return this.td108;
	}

	public void setTd108(Integer td108) {
		this.td108 = td108;
	}

	@Column(name = "td109")
	public Integer getTd109() {
		return this.td109;
	}

	public void setTd109(Integer td109) {
		this.td109 = td109;
	}

	@Column(name = "td110")
	public Integer getTd110() {
		return this.td110;
	}

	public void setTd110(Integer td110) {
		this.td110 = td110;
	}

	@Column(name = "td111")
	public Integer getTd111() {
		return this.td111;
	}

	public void setTd111(Integer td111) {
		this.td111 = td111;
	}

	@Column(name = "td112")
	public Integer getTd112() {
		return this.td112;
	}

	public void setTd112(Integer td112) {
		this.td112 = td112;
	}

	@Column(name = "td113")
	public Integer getTd113() {
		return this.td113;
	}

	public void setTd113(Integer td113) {
		this.td113 = td113;
	}

	@Column(name = "td114")
	public Integer getTd114() {
		return this.td114;
	}

	public void setTd114(Integer td114) {
		this.td114 = td114;
	}

	@Column(name = "td115")
	public Integer getTd115() {
		return this.td115;
	}

	public void setTd115(Integer td115) {
		this.td115 = td115;
	}

	@Column(name = "td116")
	public Integer getTd116() {
		return this.td116;
	}

	public void setTd116(Integer td116) {
		this.td116 = td116;
	}

	@Column(name = "td117")
	public Integer getTd117() {
		return this.td117;
	}

	public void setTd117(Integer td117) {
		this.td117 = td117;
	}

	@Column(name = "td118")
	public Integer getTd118() {
		return this.td118;
	}

	public void setTd118(Integer td118) {
		this.td118 = td118;
	}

	@Column(name = "td119")
	public Integer getTd119() {
		return this.td119;
	}

	public void setTd119(Integer td119) {
		this.td119 = td119;
	}

	@Column(name = "td120")
	public Integer getTd120() {
		return this.td120;
	}

	public void setTd120(Integer td120) {
		this.td120 = td120;
	}

	@Column(name = "td121")
	public Integer getTd121() {
		return this.td121;
	}

	public void setTd121(Integer td121) {
		this.td121 = td121;
	}

	@Column(name = "td122")
	public Integer getTd122() {
		return this.td122;
	}

	public void setTd122(Integer td122) {
		this.td122 = td122;
	}

	@Column(name = "td123")
	public Integer getTd123() {
		return this.td123;
	}

	public void setTd123(Integer td123) {
		this.td123 = td123;
	}

	@Column(name = "td124")
	public Integer getTd124() {
		return this.td124;
	}

	public void setTd124(Integer td124) {
		this.td124 = td124;
	}

	@Column(name = "td125")
	public Integer getTd125() {
		return this.td125;
	}

	public void setTd125(Integer td125) {
		this.td125 = td125;
	}

	@Column(name = "td126")
	public Integer getTd126() {
		return this.td126;
	}

	public void setTd126(Integer td126) {
		this.td126 = td126;
	}

	@Column(name = "td127")
	public Integer getTd127() {
		return this.td127;
	}

	public void setTd127(Integer td127) {
		this.td127 = td127;
	}

	@Column(name = "td128")
	public Integer getTd128() {
		return this.td128;
	}

	public void setTd128(Integer td128) {
		this.td128 = td128;
	}

	@Column(name = "td129")
	public Integer getTd129() {
		return this.td129;
	}

	public void setTd129(Integer td129) {
		this.td129 = td129;
	}

	@Column(name = "td130")
	public Integer getTd130() {
		return this.td130;
	}

	public void setTd130(Integer td130) {
		this.td130 = td130;
	}

	@Column(name = "td131")
	public Integer getTd131() {
		return this.td131;
	}

	public void setTd131(Integer td131) {
		this.td131 = td131;
	}

	@Column(name = "td132")
	public Integer getTd132() {
		return this.td132;
	}

	public void setTd132(Integer td132) {
		this.td132 = td132;
	}

}
