package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Projectdevelopment generated by hbm2java
 */
@Entity
@Table(name = "projectdevelopment", catalog = "audit", uniqueConstraints = @UniqueConstraint(columnNames = "year"))
public class ProjectDevelopment implements java.io.Serializable {

	private Integer id;
	private int year;
	private int state;
	private String sumbitOne;
	private String sumbitDate;
	private String name;
	private int editDpt;
	private Integer dptName;
	private Integer td1;
	private Integer td2;
	private Integer td3;
	private Integer td4;
	private Integer td5;
	private Integer td6;
	private Integer td7;
	private Integer td8;
	private Integer td9;
	private Integer td10;
	private Integer td11;
	private Integer td12;
	private Integer td13;
	private Integer td14;
	private Integer td15;
	private Integer td16;
	private Integer td17;
	private Integer td18;
	private Integer td19;
	private Integer td20;
	private Integer td21;
	private Integer td22;
	private Integer td23;
	private Integer td24;
	private Integer td25;
	private Integer td26;
	private Integer td27;
	private Integer td28;
	private Integer td29;
	private Integer td30;
	private Integer td31;
	private Integer td32;
	private Integer td33;
	private Integer td34;
	private Integer td35;
	private Integer td36;
	private Integer td37;
	private Integer td38;
	private Integer td39;
	private Integer td40;
	private Integer td41;
	private Integer td42;
	private Integer td43;
	private Integer td44;
	private Integer td45;
	private Integer td46;
	private Integer td47;
	private Integer td48;
	private Integer td49;
	private Integer td50;
	private Integer td51;
	private Integer td52;
	private Integer td53;
	private Integer td54;
	private Integer td55;
	private Integer td56;
	private Integer td57;
	private Integer td58;
	private Integer td59;
	private Integer td60;
	private Integer td61;
	private Integer td62;
	private Integer td63;
	private Integer td64;
	private Integer td65;
	private Integer td66;
	private Integer td67;
	private Integer td68;
	private Integer td69;
	private Integer td70;
	private Integer td71;
	private Integer td72;
	private Integer td73;
	private Integer td74;
	private Integer td75;
	private Integer td76;
	private Integer td77;
	private Integer td78;
	private Integer td79;
	private Integer td80;
	private Integer td81;
	private Integer td82;
	private Integer td83;
	private Integer td84;
	private Integer td85;
	private Integer td86;
	private Integer td87;
	private Integer td88;
	private Integer td89;
	private Integer td90;
	private Integer td91;
	private Integer td92;
	private Integer td93;
	private Integer td94;
	private Integer td95;
	private Integer td96;
	private Integer td97;
	private Integer td98;
	private Integer td99;
	private Integer td100;
	private Integer td101;
	private Integer td102;
	private Integer td103;
	private Integer td104;
	private Integer td105;
	private Integer td106;
	private Integer td107;
	private Integer td108;
	private Integer td109;
	private Integer td110;
	private Integer td111;
	private Integer td112;
	private Integer td113;
	private Integer td114;
	private Integer td115;
	private Integer td116;
	private Integer td117;
	private Integer td118;
	private Integer td119;
	private Integer td120;
	private Integer td121;
	private Integer td122;
	private Integer td123;
	private Integer td124;
	private Integer td125;
	private Integer td126;
	private Integer td127;
	private Integer td128;
	private Integer td129;
	private Integer td130;
	private Integer td131;
	private Integer td132;
	private Integer td133;
	private Integer td134;
	private Integer td135;
	private Integer td136;
	private Integer td137;
	private Integer td138;
	private Integer td139;
	private Integer td140;
	private Integer td141;
	private Integer td142;
	private Integer td143;
	private Integer td144;
	private Integer td145;
	private Integer td146;
	private Integer td147;
	private Integer td148;
	private Integer td149;
	private Integer td150;
	private Integer td151;
	private Integer td152;
	private Integer td153;
	private Integer td154;
	private Integer td155;
	private Integer td156;
	private Integer td157;
	private Integer td158;
	private Integer td159;
	private Integer td160;
	private Integer td161;
	private Integer td162;
	private Integer td163;
	private Integer td164;
	private Integer td165;
	private Integer td166;
	private Integer td167;
	private Integer td168;
	private Integer td169;
	private Integer td170;
	private Integer td171;
	private Integer td172;
	private Integer td173;
	private Integer td174;
	private Integer td175;
	private Integer td176;
	private Integer td177;
	private Integer td178;
	private Integer td179;
	private Integer td180;
	private Integer td181;
	private Integer td182;
	private Integer td183;
	private Integer td184;
	private Integer td185;
	private Integer td186;
	private Integer td187;
	private Integer td188;
	private Integer td189;
	private Integer td190;
	private Integer td191;
	private Integer td192;
	private Integer td193;
	private Integer td194;
	private Integer td195;
	private Integer td196;
	private Integer td197;
	private Integer td198;
	private Integer td199;
	private Integer td200;
	private Integer td201;
	private Integer td202;
	private Integer td203;
	private Integer td204;
	private Integer td205;
	private Integer td206;
	private Integer td207;
	private Integer td208;
	private Integer td209;
	private Integer td210;
	private Integer td211;
	private Integer td212;
	private Integer td213;
	private Integer td214;
	private Integer td215;
	private Integer td216;
	private Integer td217;
	private Integer td218;
	private Integer td219;
	private Integer td220;
	private Integer td221;
	private Integer td222;
	private Integer td223;
	private Integer td224;
	private Integer td225;
	private Integer td226;
	private Integer td227;
	private Integer td228;
	private Integer td229;
	private Integer td230;
	private Integer td231;
	private Integer td232;
	private Integer td233;
	private Integer td234;
	private Integer td235;
	private Integer td236;
	private Integer td237;
	private Integer td238;
	private Integer td239;
	private Integer td240;

	public ProjectDevelopment() {
	}

	public ProjectDevelopment(int year, int state, String sumbitOne, String name, int editDpt) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.name = name;
		this.editDpt = editDpt;
	}

	public ProjectDevelopment(int year, int state, String sumbitOne, String sumbitDate, String name, int editDpt,
			Integer dptName, Integer td1, Integer td2, Integer td3, Integer td4, Integer td5, Integer td6, Integer td7,
			Integer td8, Integer td9, Integer td10, Integer td11, Integer td12, Integer td13, Integer td14,
			Integer td15, Integer td16, Integer td17, Integer td18, Integer td19, Integer td20, Integer td21,
			Integer td22, Integer td23, Integer td24, Integer td25, Integer td26, Integer td27, Integer td28,
			Integer td29, Integer td30, Integer td31, Integer td32, Integer td33, Integer td34, Integer td35,
			Integer td36, Integer td37, Integer td38, Integer td39, Integer td40, Integer td41, Integer td42,
			Integer td43, Integer td44, Integer td45, Integer td46, Integer td47, Integer td48, Integer td49,
			Integer td50, Integer td51, Integer td52, Integer td53, Integer td54, Integer td55, Integer td56,
			Integer td57, Integer td58, Integer td59, Integer td60, Integer td61, Integer td62, Integer td63,
			Integer td64, Integer td65, Integer td66, Integer td67, Integer td68, Integer td69, Integer td70,
			Integer td71, Integer td72, Integer td73, Integer td74, Integer td75, Integer td76, Integer td77,
			Integer td78, Integer td79, Integer td80, Integer td81, Integer td82, Integer td83, Integer td84,
			Integer td85, Integer td86, Integer td87, Integer td88, Integer td89, Integer td90, Integer td91,
			Integer td92, Integer td93, Integer td94, Integer td95, Integer td96, Integer td97, Integer td98,
			Integer td99, Integer td100, Integer td101, Integer td102, Integer td103, Integer td104, Integer td105,
			Integer td106, Integer td107, Integer td108, Integer td109, Integer td110, Integer td111, Integer td112,
			Integer td113, Integer td114, Integer td115, Integer td116, Integer td117, Integer td118, Integer td119,
			Integer td120, Integer td121, Integer td122, Integer td123, Integer td124, Integer td125, Integer td126,
			Integer td127, Integer td128, Integer td129, Integer td130, Integer td131, Integer td132, Integer td133,
			Integer td134, Integer td135, Integer td136, Integer td137, Integer td138, Integer td139, Integer td140,
			Integer td141, Integer td142, Integer td143, Integer td144, Integer td145, Integer td146, Integer td147,
			Integer td148, Integer td149, Integer td150, Integer td151, Integer td152, Integer td153, Integer td154,
			Integer td155, Integer td156, Integer td157, Integer td158, Integer td159, Integer td160, Integer td161,
			Integer td162, Integer td163, Integer td164, Integer td165, Integer td166, Integer td167, Integer td168,
			Integer td169, Integer td170, Integer td171, Integer td172, Integer td173, Integer td174, Integer td175,
			Integer td176, Integer td177, Integer td178, Integer td179, Integer td180, Integer td181, Integer td182,
			Integer td183, Integer td184, Integer td185, Integer td186, Integer td187, Integer td188, Integer td189,
			Integer td190, Integer td191, Integer td192, Integer td193, Integer td194, Integer td195, Integer td196,
			Integer td197, Integer td198, Integer td199, Integer td200, Integer td201, Integer td202, Integer td203,
			Integer td204, Integer td205, Integer td206, Integer td207, Integer td208, Integer td209, Integer td210,
			Integer td211, Integer td212, Integer td213, Integer td214, Integer td215, Integer td216, Integer td217,
			Integer td218, Integer td219, Integer td220, Integer td221, Integer td222, Integer td223, Integer td224,
			Integer td225, Integer td226, Integer td227, Integer td228, Integer td229, Integer td230, Integer td231,
			Integer td232, Integer td233, Integer td234, Integer td235, Integer td236, Integer td237, Integer td238,
			Integer td239, Integer td240) {
		this.year = year;
		this.state = state;
		this.sumbitOne = sumbitOne;
		this.sumbitDate = sumbitDate;
		this.name = name;
		this.editDpt = editDpt;
		this.dptName = dptName;
		this.td1 = td1;
		this.td2 = td2;
		this.td3 = td3;
		this.td4 = td4;
		this.td5 = td5;
		this.td6 = td6;
		this.td7 = td7;
		this.td8 = td8;
		this.td9 = td9;
		this.td10 = td10;
		this.td11 = td11;
		this.td12 = td12;
		this.td13 = td13;
		this.td14 = td14;
		this.td15 = td15;
		this.td16 = td16;
		this.td17 = td17;
		this.td18 = td18;
		this.td19 = td19;
		this.td20 = td20;
		this.td21 = td21;
		this.td22 = td22;
		this.td23 = td23;
		this.td24 = td24;
		this.td25 = td25;
		this.td26 = td26;
		this.td27 = td27;
		this.td28 = td28;
		this.td29 = td29;
		this.td30 = td30;
		this.td31 = td31;
		this.td32 = td32;
		this.td33 = td33;
		this.td34 = td34;
		this.td35 = td35;
		this.td36 = td36;
		this.td37 = td37;
		this.td38 = td38;
		this.td39 = td39;
		this.td40 = td40;
		this.td41 = td41;
		this.td42 = td42;
		this.td43 = td43;
		this.td44 = td44;
		this.td45 = td45;
		this.td46 = td46;
		this.td47 = td47;
		this.td48 = td48;
		this.td49 = td49;
		this.td50 = td50;
		this.td51 = td51;
		this.td52 = td52;
		this.td53 = td53;
		this.td54 = td54;
		this.td55 = td55;
		this.td56 = td56;
		this.td57 = td57;
		this.td58 = td58;
		this.td59 = td59;
		this.td60 = td60;
		this.td61 = td61;
		this.td62 = td62;
		this.td63 = td63;
		this.td64 = td64;
		this.td65 = td65;
		this.td66 = td66;
		this.td67 = td67;
		this.td68 = td68;
		this.td69 = td69;
		this.td70 = td70;
		this.td71 = td71;
		this.td72 = td72;
		this.td73 = td73;
		this.td74 = td74;
		this.td75 = td75;
		this.td76 = td76;
		this.td77 = td77;
		this.td78 = td78;
		this.td79 = td79;
		this.td80 = td80;
		this.td81 = td81;
		this.td82 = td82;
		this.td83 = td83;
		this.td84 = td84;
		this.td85 = td85;
		this.td86 = td86;
		this.td87 = td87;
		this.td88 = td88;
		this.td89 = td89;
		this.td90 = td90;
		this.td91 = td91;
		this.td92 = td92;
		this.td93 = td93;
		this.td94 = td94;
		this.td95 = td95;
		this.td96 = td96;
		this.td97 = td97;
		this.td98 = td98;
		this.td99 = td99;
		this.td100 = td100;
		this.td101 = td101;
		this.td102 = td102;
		this.td103 = td103;
		this.td104 = td104;
		this.td105 = td105;
		this.td106 = td106;
		this.td107 = td107;
		this.td108 = td108;
		this.td109 = td109;
		this.td110 = td110;
		this.td111 = td111;
		this.td112 = td112;
		this.td113 = td113;
		this.td114 = td114;
		this.td115 = td115;
		this.td116 = td116;
		this.td117 = td117;
		this.td118 = td118;
		this.td119 = td119;
		this.td120 = td120;
		this.td121 = td121;
		this.td122 = td122;
		this.td123 = td123;
		this.td124 = td124;
		this.td125 = td125;
		this.td126 = td126;
		this.td127 = td127;
		this.td128 = td128;
		this.td129 = td129;
		this.td130 = td130;
		this.td131 = td131;
		this.td132 = td132;
		this.td133 = td133;
		this.td134 = td134;
		this.td135 = td135;
		this.td136 = td136;
		this.td137 = td137;
		this.td138 = td138;
		this.td139 = td139;
		this.td140 = td140;
		this.td141 = td141;
		this.td142 = td142;
		this.td143 = td143;
		this.td144 = td144;
		this.td145 = td145;
		this.td146 = td146;
		this.td147 = td147;
		this.td148 = td148;
		this.td149 = td149;
		this.td150 = td150;
		this.td151 = td151;
		this.td152 = td152;
		this.td153 = td153;
		this.td154 = td154;
		this.td155 = td155;
		this.td156 = td156;
		this.td157 = td157;
		this.td158 = td158;
		this.td159 = td159;
		this.td160 = td160;
		this.td161 = td161;
		this.td162 = td162;
		this.td163 = td163;
		this.td164 = td164;
		this.td165 = td165;
		this.td166 = td166;
		this.td167 = td167;
		this.td168 = td168;
		this.td169 = td169;
		this.td170 = td170;
		this.td171 = td171;
		this.td172 = td172;
		this.td173 = td173;
		this.td174 = td174;
		this.td175 = td175;
		this.td176 = td176;
		this.td177 = td177;
		this.td178 = td178;
		this.td179 = td179;
		this.td180 = td180;
		this.td181 = td181;
		this.td182 = td182;
		this.td183 = td183;
		this.td184 = td184;
		this.td185 = td185;
		this.td186 = td186;
		this.td187 = td187;
		this.td188 = td188;
		this.td189 = td189;
		this.td190 = td190;
		this.td191 = td191;
		this.td192 = td192;
		this.td193 = td193;
		this.td194 = td194;
		this.td195 = td195;
		this.td196 = td196;
		this.td197 = td197;
		this.td198 = td198;
		this.td199 = td199;
		this.td200 = td200;
		this.td201 = td201;
		this.td202 = td202;
		this.td203 = td203;
		this.td204 = td204;
		this.td205 = td205;
		this.td206 = td206;
		this.td207 = td207;
		this.td208 = td208;
		this.td209 = td209;
		this.td210 = td210;
		this.td211 = td211;
		this.td212 = td212;
		this.td213 = td213;
		this.td214 = td214;
		this.td215 = td215;
		this.td216 = td216;
		this.td217 = td217;
		this.td218 = td218;
		this.td219 = td219;
		this.td220 = td220;
		this.td221 = td221;
		this.td222 = td222;
		this.td223 = td223;
		this.td224 = td224;
		this.td225 = td225;
		this.td226 = td226;
		this.td227 = td227;
		this.td228 = td228;
		this.td229 = td229;
		this.td230 = td230;
		this.td231 = td231;
		this.td232 = td232;
		this.td233 = td233;
		this.td234 = td234;
		this.td235 = td235;
		this.td236 = td236;
		this.td237 = td237;
		this.td238 = td238;
		this.td239 = td239;
		this.td240 = td240;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year", unique = true, nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "sumbitOne", nullable = false, length = 12)
	public String getSumbitOne() {
		return this.sumbitOne;
	}

	public void setSumbitOne(String sumbitOne) {
		this.sumbitOne = sumbitOne;
	}

	@Column(name = "sumbitDate", length = 32)
	public String getSumbitDate() {
		return this.sumbitDate;
	}

	public void setSumbitDate(String sumbitDate) {
		this.sumbitDate = sumbitDate;
	}

	@Column(name = "name", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "editDpt", nullable = false)
	public int getEditDpt() {
		return this.editDpt;
	}

	public void setEditDpt(int editDpt) {
		this.editDpt = editDpt;
	}

	@Column(name = "dptName")
	public Integer getDptName() {
		return this.dptName;
	}

	public void setDptName(Integer dptName) {
		this.dptName = dptName;
	}

	@Column(name = "td1")
	public Integer getTd1() {
		return this.td1;
	}

	public void setTd1(Integer td1) {
		this.td1 = td1;
	}

	@Column(name = "td2")
	public Integer getTd2() {
		return this.td2;
	}

	public void setTd2(Integer td2) {
		this.td2 = td2;
	}

	@Column(name = "td3")
	public Integer getTd3() {
		return this.td3;
	}

	public void setTd3(Integer td3) {
		this.td3 = td3;
	}

	@Column(name = "td4")
	public Integer getTd4() {
		return this.td4;
	}

	public void setTd4(Integer td4) {
		this.td4 = td4;
	}

	@Column(name = "td5")
	public Integer getTd5() {
		return this.td5;
	}

	public void setTd5(Integer td5) {
		this.td5 = td5;
	}

	@Column(name = "td6")
	public Integer getTd6() {
		return this.td6;
	}

	public void setTd6(Integer td6) {
		this.td6 = td6;
	}

	@Column(name = "td7")
	public Integer getTd7() {
		return this.td7;
	}

	public void setTd7(Integer td7) {
		this.td7 = td7;
	}

	@Column(name = "td8")
	public Integer getTd8() {
		return this.td8;
	}

	public void setTd8(Integer td8) {
		this.td8 = td8;
	}

	@Column(name = "td9")
	public Integer getTd9() {
		return this.td9;
	}

	public void setTd9(Integer td9) {
		this.td9 = td9;
	}

	@Column(name = "td10")
	public Integer getTd10() {
		return this.td10;
	}

	public void setTd10(Integer td10) {
		this.td10 = td10;
	}

	@Column(name = "td11")
	public Integer getTd11() {
		return this.td11;
	}

	public void setTd11(Integer td11) {
		this.td11 = td11;
	}

	@Column(name = "td12")
	public Integer getTd12() {
		return this.td12;
	}

	public void setTd12(Integer td12) {
		this.td12 = td12;
	}

	@Column(name = "td13")
	public Integer getTd13() {
		return this.td13;
	}

	public void setTd13(Integer td13) {
		this.td13 = td13;
	}

	@Column(name = "td14")
	public Integer getTd14() {
		return this.td14;
	}

	public void setTd14(Integer td14) {
		this.td14 = td14;
	}

	@Column(name = "td15")
	public Integer getTd15() {
		return this.td15;
	}

	public void setTd15(Integer td15) {
		this.td15 = td15;
	}

	@Column(name = "td16")
	public Integer getTd16() {
		return this.td16;
	}

	public void setTd16(Integer td16) {
		this.td16 = td16;
	}

	@Column(name = "td17")
	public Integer getTd17() {
		return this.td17;
	}

	public void setTd17(Integer td17) {
		this.td17 = td17;
	}

	@Column(name = "td18")
	public Integer getTd18() {
		return this.td18;
	}

	public void setTd18(Integer td18) {
		this.td18 = td18;
	}

	@Column(name = "td19")
	public Integer getTd19() {
		return this.td19;
	}

	public void setTd19(Integer td19) {
		this.td19 = td19;
	}

	@Column(name = "td20")
	public Integer getTd20() {
		return this.td20;
	}

	public void setTd20(Integer td20) {
		this.td20 = td20;
	}

	@Column(name = "td21")
	public Integer getTd21() {
		return this.td21;
	}

	public void setTd21(Integer td21) {
		this.td21 = td21;
	}

	@Column(name = "td22")
	public Integer getTd22() {
		return this.td22;
	}

	public void setTd22(Integer td22) {
		this.td22 = td22;
	}

	@Column(name = "td23")
	public Integer getTd23() {
		return this.td23;
	}

	public void setTd23(Integer td23) {
		this.td23 = td23;
	}

	@Column(name = "td24")
	public Integer getTd24() {
		return this.td24;
	}

	public void setTd24(Integer td24) {
		this.td24 = td24;
	}

	@Column(name = "td25")
	public Integer getTd25() {
		return this.td25;
	}

	public void setTd25(Integer td25) {
		this.td25 = td25;
	}

	@Column(name = "td26")
	public Integer getTd26() {
		return this.td26;
	}

	public void setTd26(Integer td26) {
		this.td26 = td26;
	}

	@Column(name = "td27")
	public Integer getTd27() {
		return this.td27;
	}

	public void setTd27(Integer td27) {
		this.td27 = td27;
	}

	@Column(name = "td28")
	public Integer getTd28() {
		return this.td28;
	}

	public void setTd28(Integer td28) {
		this.td28 = td28;
	}

	@Column(name = "td29")
	public Integer getTd29() {
		return this.td29;
	}

	public void setTd29(Integer td29) {
		this.td29 = td29;
	}

	@Column(name = "td30")
	public Integer getTd30() {
		return this.td30;
	}

	public void setTd30(Integer td30) {
		this.td30 = td30;
	}

	@Column(name = "td31")
	public Integer getTd31() {
		return this.td31;
	}

	public void setTd31(Integer td31) {
		this.td31 = td31;
	}

	@Column(name = "td32")
	public Integer getTd32() {
		return this.td32;
	}

	public void setTd32(Integer td32) {
		this.td32 = td32;
	}

	@Column(name = "td33")
	public Integer getTd33() {
		return this.td33;
	}

	public void setTd33(Integer td33) {
		this.td33 = td33;
	}

	@Column(name = "td34")
	public Integer getTd34() {
		return this.td34;
	}

	public void setTd34(Integer td34) {
		this.td34 = td34;
	}

	@Column(name = "td35")
	public Integer getTd35() {
		return this.td35;
	}

	public void setTd35(Integer td35) {
		this.td35 = td35;
	}

	@Column(name = "td36")
	public Integer getTd36() {
		return this.td36;
	}

	public void setTd36(Integer td36) {
		this.td36 = td36;
	}

	@Column(name = "td37")
	public Integer getTd37() {
		return this.td37;
	}

	public void setTd37(Integer td37) {
		this.td37 = td37;
	}

	@Column(name = "td38")
	public Integer getTd38() {
		return this.td38;
	}

	public void setTd38(Integer td38) {
		this.td38 = td38;
	}

	@Column(name = "td39")
	public Integer getTd39() {
		return this.td39;
	}

	public void setTd39(Integer td39) {
		this.td39 = td39;
	}

	@Column(name = "td40")
	public Integer getTd40() {
		return this.td40;
	}

	public void setTd40(Integer td40) {
		this.td40 = td40;
	}

	@Column(name = "td41")
	public Integer getTd41() {
		return this.td41;
	}

	public void setTd41(Integer td41) {
		this.td41 = td41;
	}

	@Column(name = "td42")
	public Integer getTd42() {
		return this.td42;
	}

	public void setTd42(Integer td42) {
		this.td42 = td42;
	}

	@Column(name = "td43")
	public Integer getTd43() {
		return this.td43;
	}

	public void setTd43(Integer td43) {
		this.td43 = td43;
	}

	@Column(name = "td44")
	public Integer getTd44() {
		return this.td44;
	}

	public void setTd44(Integer td44) {
		this.td44 = td44;
	}

	@Column(name = "td45")
	public Integer getTd45() {
		return this.td45;
	}

	public void setTd45(Integer td45) {
		this.td45 = td45;
	}

	@Column(name = "td46")
	public Integer getTd46() {
		return this.td46;
	}

	public void setTd46(Integer td46) {
		this.td46 = td46;
	}

	@Column(name = "td47")
	public Integer getTd47() {
		return this.td47;
	}

	public void setTd47(Integer td47) {
		this.td47 = td47;
	}

	@Column(name = "td48")
	public Integer getTd48() {
		return this.td48;
	}

	public void setTd48(Integer td48) {
		this.td48 = td48;
	}

	@Column(name = "td49")
	public Integer getTd49() {
		return this.td49;
	}

	public void setTd49(Integer td49) {
		this.td49 = td49;
	}

	@Column(name = "td50")
	public Integer getTd50() {
		return this.td50;
	}

	public void setTd50(Integer td50) {
		this.td50 = td50;
	}

	@Column(name = "td51")
	public Integer getTd51() {
		return this.td51;
	}

	public void setTd51(Integer td51) {
		this.td51 = td51;
	}

	@Column(name = "td52")
	public Integer getTd52() {
		return this.td52;
	}

	public void setTd52(Integer td52) {
		this.td52 = td52;
	}

	@Column(name = "td53")
	public Integer getTd53() {
		return this.td53;
	}

	public void setTd53(Integer td53) {
		this.td53 = td53;
	}

	@Column(name = "td54")
	public Integer getTd54() {
		return this.td54;
	}

	public void setTd54(Integer td54) {
		this.td54 = td54;
	}

	@Column(name = "td55")
	public Integer getTd55() {
		return this.td55;
	}

	public void setTd55(Integer td55) {
		this.td55 = td55;
	}

	@Column(name = "td56")
	public Integer getTd56() {
		return this.td56;
	}

	public void setTd56(Integer td56) {
		this.td56 = td56;
	}

	@Column(name = "td57")
	public Integer getTd57() {
		return this.td57;
	}

	public void setTd57(Integer td57) {
		this.td57 = td57;
	}

	@Column(name = "td58")
	public Integer getTd58() {
		return this.td58;
	}

	public void setTd58(Integer td58) {
		this.td58 = td58;
	}

	@Column(name = "td59")
	public Integer getTd59() {
		return this.td59;
	}

	public void setTd59(Integer td59) {
		this.td59 = td59;
	}

	@Column(name = "td60")
	public Integer getTd60() {
		return this.td60;
	}

	public void setTd60(Integer td60) {
		this.td60 = td60;
	}

	@Column(name = "td61")
	public Integer getTd61() {
		return this.td61;
	}

	public void setTd61(Integer td61) {
		this.td61 = td61;
	}

	@Column(name = "td62")
	public Integer getTd62() {
		return this.td62;
	}

	public void setTd62(Integer td62) {
		this.td62 = td62;
	}

	@Column(name = "td63")
	public Integer getTd63() {
		return this.td63;
	}

	public void setTd63(Integer td63) {
		this.td63 = td63;
	}

	@Column(name = "td64")
	public Integer getTd64() {
		return this.td64;
	}

	public void setTd64(Integer td64) {
		this.td64 = td64;
	}

	@Column(name = "td65")
	public Integer getTd65() {
		return this.td65;
	}

	public void setTd65(Integer td65) {
		this.td65 = td65;
	}

	@Column(name = "td66")
	public Integer getTd66() {
		return this.td66;
	}

	public void setTd66(Integer td66) {
		this.td66 = td66;
	}

	@Column(name = "td67")
	public Integer getTd67() {
		return this.td67;
	}

	public void setTd67(Integer td67) {
		this.td67 = td67;
	}

	@Column(name = "td68")
	public Integer getTd68() {
		return this.td68;
	}

	public void setTd68(Integer td68) {
		this.td68 = td68;
	}

	@Column(name = "td69")
	public Integer getTd69() {
		return this.td69;
	}

	public void setTd69(Integer td69) {
		this.td69 = td69;
	}

	@Column(name = "td70")
	public Integer getTd70() {
		return this.td70;
	}

	public void setTd70(Integer td70) {
		this.td70 = td70;
	}

	@Column(name = "td71")
	public Integer getTd71() {
		return this.td71;
	}

	public void setTd71(Integer td71) {
		this.td71 = td71;
	}

	@Column(name = "td72")
	public Integer getTd72() {
		return this.td72;
	}

	public void setTd72(Integer td72) {
		this.td72 = td72;
	}

	@Column(name = "td73")
	public Integer getTd73() {
		return this.td73;
	}

	public void setTd73(Integer td73) {
		this.td73 = td73;
	}

	@Column(name = "td74")
	public Integer getTd74() {
		return this.td74;
	}

	public void setTd74(Integer td74) {
		this.td74 = td74;
	}

	@Column(name = "td75")
	public Integer getTd75() {
		return this.td75;
	}

	public void setTd75(Integer td75) {
		this.td75 = td75;
	}

	@Column(name = "td76")
	public Integer getTd76() {
		return this.td76;
	}

	public void setTd76(Integer td76) {
		this.td76 = td76;
	}

	@Column(name = "td77")
	public Integer getTd77() {
		return this.td77;
	}

	public void setTd77(Integer td77) {
		this.td77 = td77;
	}

	@Column(name = "td78")
	public Integer getTd78() {
		return this.td78;
	}

	public void setTd78(Integer td78) {
		this.td78 = td78;
	}

	@Column(name = "td79")
	public Integer getTd79() {
		return this.td79;
	}

	public void setTd79(Integer td79) {
		this.td79 = td79;
	}

	@Column(name = "td80")
	public Integer getTd80() {
		return this.td80;
	}

	public void setTd80(Integer td80) {
		this.td80 = td80;
	}

	@Column(name = "td81")
	public Integer getTd81() {
		return this.td81;
	}

	public void setTd81(Integer td81) {
		this.td81 = td81;
	}

	@Column(name = "td82")
	public Integer getTd82() {
		return this.td82;
	}

	public void setTd82(Integer td82) {
		this.td82 = td82;
	}

	@Column(name = "td83")
	public Integer getTd83() {
		return this.td83;
	}

	public void setTd83(Integer td83) {
		this.td83 = td83;
	}

	@Column(name = "td84")
	public Integer getTd84() {
		return this.td84;
	}

	public void setTd84(Integer td84) {
		this.td84 = td84;
	}

	@Column(name = "td85")
	public Integer getTd85() {
		return this.td85;
	}

	public void setTd85(Integer td85) {
		this.td85 = td85;
	}

	@Column(name = "td86")
	public Integer getTd86() {
		return this.td86;
	}

	public void setTd86(Integer td86) {
		this.td86 = td86;
	}

	@Column(name = "td87")
	public Integer getTd87() {
		return this.td87;
	}

	public void setTd87(Integer td87) {
		this.td87 = td87;
	}

	@Column(name = "td88")
	public Integer getTd88() {
		return this.td88;
	}

	public void setTd88(Integer td88) {
		this.td88 = td88;
	}

	@Column(name = "td89")
	public Integer getTd89() {
		return this.td89;
	}

	public void setTd89(Integer td89) {
		this.td89 = td89;
	}

	@Column(name = "td90")
	public Integer getTd90() {
		return this.td90;
	}

	public void setTd90(Integer td90) {
		this.td90 = td90;
	}

	@Column(name = "td91")
	public Integer getTd91() {
		return this.td91;
	}

	public void setTd91(Integer td91) {
		this.td91 = td91;
	}

	@Column(name = "td92")
	public Integer getTd92() {
		return this.td92;
	}

	public void setTd92(Integer td92) {
		this.td92 = td92;
	}

	@Column(name = "td93")
	public Integer getTd93() {
		return this.td93;
	}

	public void setTd93(Integer td93) {
		this.td93 = td93;
	}

	@Column(name = "td94")
	public Integer getTd94() {
		return this.td94;
	}

	public void setTd94(Integer td94) {
		this.td94 = td94;
	}

	@Column(name = "td95")
	public Integer getTd95() {
		return this.td95;
	}

	public void setTd95(Integer td95) {
		this.td95 = td95;
	}

	@Column(name = "td96")
	public Integer getTd96() {
		return this.td96;
	}

	public void setTd96(Integer td96) {
		this.td96 = td96;
	}

	@Column(name = "td97")
	public Integer getTd97() {
		return this.td97;
	}

	public void setTd97(Integer td97) {
		this.td97 = td97;
	}

	@Column(name = "td98")
	public Integer getTd98() {
		return this.td98;
	}

	public void setTd98(Integer td98) {
		this.td98 = td98;
	}

	@Column(name = "td99")
	public Integer getTd99() {
		return this.td99;
	}

	public void setTd99(Integer td99) {
		this.td99 = td99;
	}

	@Column(name = "td100")
	public Integer getTd100() {
		return this.td100;
	}

	public void setTd100(Integer td100) {
		this.td100 = td100;
	}

	@Column(name = "td101")
	public Integer getTd101() {
		return this.td101;
	}

	public void setTd101(Integer td101) {
		this.td101 = td101;
	}

	@Column(name = "td102")
	public Integer getTd102() {
		return this.td102;
	}

	public void setTd102(Integer td102) {
		this.td102 = td102;
	}

	@Column(name = "td103")
	public Integer getTd103() {
		return this.td103;
	}

	public void setTd103(Integer td103) {
		this.td103 = td103;
	}

	@Column(name = "td104")
	public Integer getTd104() {
		return this.td104;
	}

	public void setTd104(Integer td104) {
		this.td104 = td104;
	}

	@Column(name = "td105")
	public Integer getTd105() {
		return this.td105;
	}

	public void setTd105(Integer td105) {
		this.td105 = td105;
	}

	@Column(name = "td106")
	public Integer getTd106() {
		return this.td106;
	}

	public void setTd106(Integer td106) {
		this.td106 = td106;
	}

	@Column(name = "td107")
	public Integer getTd107() {
		return this.td107;
	}

	public void setTd107(Integer td107) {
		this.td107 = td107;
	}

	@Column(name = "td108")
	public Integer getTd108() {
		return this.td108;
	}

	public void setTd108(Integer td108) {
		this.td108 = td108;
	}

	@Column(name = "td109")
	public Integer getTd109() {
		return this.td109;
	}

	public void setTd109(Integer td109) {
		this.td109 = td109;
	}

	@Column(name = "td110")
	public Integer getTd110() {
		return this.td110;
	}

	public void setTd110(Integer td110) {
		this.td110 = td110;
	}

	@Column(name = "td111")
	public Integer getTd111() {
		return this.td111;
	}

	public void setTd111(Integer td111) {
		this.td111 = td111;
	}

	@Column(name = "td112")
	public Integer getTd112() {
		return this.td112;
	}

	public void setTd112(Integer td112) {
		this.td112 = td112;
	}

	@Column(name = "td113")
	public Integer getTd113() {
		return this.td113;
	}

	public void setTd113(Integer td113) {
		this.td113 = td113;
	}

	@Column(name = "td114")
	public Integer getTd114() {
		return this.td114;
	}

	public void setTd114(Integer td114) {
		this.td114 = td114;
	}

	@Column(name = "td115")
	public Integer getTd115() {
		return this.td115;
	}

	public void setTd115(Integer td115) {
		this.td115 = td115;
	}

	@Column(name = "td116")
	public Integer getTd116() {
		return this.td116;
	}

	public void setTd116(Integer td116) {
		this.td116 = td116;
	}

	@Column(name = "td117")
	public Integer getTd117() {
		return this.td117;
	}

	public void setTd117(Integer td117) {
		this.td117 = td117;
	}

	@Column(name = "td118")
	public Integer getTd118() {
		return this.td118;
	}

	public void setTd118(Integer td118) {
		this.td118 = td118;
	}

	@Column(name = "td119")
	public Integer getTd119() {
		return this.td119;
	}

	public void setTd119(Integer td119) {
		this.td119 = td119;
	}

	@Column(name = "td120")
	public Integer getTd120() {
		return this.td120;
	}

	public void setTd120(Integer td120) {
		this.td120 = td120;
	}

	@Column(name = "td121")
	public Integer getTd121() {
		return this.td121;
	}

	public void setTd121(Integer td121) {
		this.td121 = td121;
	}

	@Column(name = "td122")
	public Integer getTd122() {
		return this.td122;
	}

	public void setTd122(Integer td122) {
		this.td122 = td122;
	}

	@Column(name = "td123")
	public Integer getTd123() {
		return this.td123;
	}

	public void setTd123(Integer td123) {
		this.td123 = td123;
	}

	@Column(name = "td124")
	public Integer getTd124() {
		return this.td124;
	}

	public void setTd124(Integer td124) {
		this.td124 = td124;
	}

	@Column(name = "td125")
	public Integer getTd125() {
		return this.td125;
	}

	public void setTd125(Integer td125) {
		this.td125 = td125;
	}

	@Column(name = "td126")
	public Integer getTd126() {
		return this.td126;
	}

	public void setTd126(Integer td126) {
		this.td126 = td126;
	}

	@Column(name = "td127")
	public Integer getTd127() {
		return this.td127;
	}

	public void setTd127(Integer td127) {
		this.td127 = td127;
	}

	@Column(name = "td128")
	public Integer getTd128() {
		return this.td128;
	}

	public void setTd128(Integer td128) {
		this.td128 = td128;
	}

	@Column(name = "td129")
	public Integer getTd129() {
		return this.td129;
	}

	public void setTd129(Integer td129) {
		this.td129 = td129;
	}

	@Column(name = "td130")
	public Integer getTd130() {
		return this.td130;
	}

	public void setTd130(Integer td130) {
		this.td130 = td130;
	}

	@Column(name = "td131")
	public Integer getTd131() {
		return this.td131;
	}

	public void setTd131(Integer td131) {
		this.td131 = td131;
	}

	@Column(name = "td132")
	public Integer getTd132() {
		return this.td132;
	}

	public void setTd132(Integer td132) {
		this.td132 = td132;
	}

	@Column(name = "td133")
	public Integer getTd133() {
		return this.td133;
	}

	public void setTd133(Integer td133) {
		this.td133 = td133;
	}

	@Column(name = "td134")
	public Integer getTd134() {
		return this.td134;
	}

	public void setTd134(Integer td134) {
		this.td134 = td134;
	}

	@Column(name = "td135")
	public Integer getTd135() {
		return this.td135;
	}

	public void setTd135(Integer td135) {
		this.td135 = td135;
	}

	@Column(name = "td136")
	public Integer getTd136() {
		return this.td136;
	}

	public void setTd136(Integer td136) {
		this.td136 = td136;
	}

	@Column(name = "td137")
	public Integer getTd137() {
		return this.td137;
	}

	public void setTd137(Integer td137) {
		this.td137 = td137;
	}

	@Column(name = "td138")
	public Integer getTd138() {
		return this.td138;
	}

	public void setTd138(Integer td138) {
		this.td138 = td138;
	}

	@Column(name = "td139")
	public Integer getTd139() {
		return this.td139;
	}

	public void setTd139(Integer td139) {
		this.td139 = td139;
	}

	@Column(name = "td140")
	public Integer getTd140() {
		return this.td140;
	}

	public void setTd140(Integer td140) {
		this.td140 = td140;
	}

	@Column(name = "td141")
	public Integer getTd141() {
		return this.td141;
	}

	public void setTd141(Integer td141) {
		this.td141 = td141;
	}

	@Column(name = "td142")
	public Integer getTd142() {
		return this.td142;
	}

	public void setTd142(Integer td142) {
		this.td142 = td142;
	}

	@Column(name = "td143")
	public Integer getTd143() {
		return this.td143;
	}

	public void setTd143(Integer td143) {
		this.td143 = td143;
	}

	@Column(name = "td144")
	public Integer getTd144() {
		return this.td144;
	}

	public void setTd144(Integer td144) {
		this.td144 = td144;
	}

	@Column(name = "td145")
	public Integer getTd145() {
		return this.td145;
	}

	public void setTd145(Integer td145) {
		this.td145 = td145;
	}

	@Column(name = "td146")
	public Integer getTd146() {
		return this.td146;
	}

	public void setTd146(Integer td146) {
		this.td146 = td146;
	}

	@Column(name = "td147")
	public Integer getTd147() {
		return this.td147;
	}

	public void setTd147(Integer td147) {
		this.td147 = td147;
	}

	@Column(name = "td148")
	public Integer getTd148() {
		return this.td148;
	}

	public void setTd148(Integer td148) {
		this.td148 = td148;
	}

	@Column(name = "td149")
	public Integer getTd149() {
		return this.td149;
	}

	public void setTd149(Integer td149) {
		this.td149 = td149;
	}

	@Column(name = "td150")
	public Integer getTd150() {
		return this.td150;
	}

	public void setTd150(Integer td150) {
		this.td150 = td150;
	}

	@Column(name = "td151")
	public Integer getTd151() {
		return this.td151;
	}

	public void setTd151(Integer td151) {
		this.td151 = td151;
	}

	@Column(name = "td152")
	public Integer getTd152() {
		return this.td152;
	}

	public void setTd152(Integer td152) {
		this.td152 = td152;
	}

	@Column(name = "td153")
	public Integer getTd153() {
		return this.td153;
	}

	public void setTd153(Integer td153) {
		this.td153 = td153;
	}

	@Column(name = "td154")
	public Integer getTd154() {
		return this.td154;
	}

	public void setTd154(Integer td154) {
		this.td154 = td154;
	}

	@Column(name = "td155")
	public Integer getTd155() {
		return this.td155;
	}

	public void setTd155(Integer td155) {
		this.td155 = td155;
	}

	@Column(name = "td156")
	public Integer getTd156() {
		return this.td156;
	}

	public void setTd156(Integer td156) {
		this.td156 = td156;
	}

	@Column(name = "td157")
	public Integer getTd157() {
		return this.td157;
	}

	public void setTd157(Integer td157) {
		this.td157 = td157;
	}

	@Column(name = "td158")
	public Integer getTd158() {
		return this.td158;
	}

	public void setTd158(Integer td158) {
		this.td158 = td158;
	}

	@Column(name = "td159")
	public Integer getTd159() {
		return this.td159;
	}

	public void setTd159(Integer td159) {
		this.td159 = td159;
	}

	@Column(name = "td160")
	public Integer getTd160() {
		return this.td160;
	}

	public void setTd160(Integer td160) {
		this.td160 = td160;
	}

	@Column(name = "td161")
	public Integer getTd161() {
		return this.td161;
	}

	public void setTd161(Integer td161) {
		this.td161 = td161;
	}

	@Column(name = "td162")
	public Integer getTd162() {
		return this.td162;
	}

	public void setTd162(Integer td162) {
		this.td162 = td162;
	}

	@Column(name = "td163")
	public Integer getTd163() {
		return this.td163;
	}

	public void setTd163(Integer td163) {
		this.td163 = td163;
	}

	@Column(name = "td164")
	public Integer getTd164() {
		return this.td164;
	}

	public void setTd164(Integer td164) {
		this.td164 = td164;
	}

	@Column(name = "td165")
	public Integer getTd165() {
		return this.td165;
	}

	public void setTd165(Integer td165) {
		this.td165 = td165;
	}

	@Column(name = "td166")
	public Integer getTd166() {
		return this.td166;
	}

	public void setTd166(Integer td166) {
		this.td166 = td166;
	}

	@Column(name = "td167")
	public Integer getTd167() {
		return this.td167;
	}

	public void setTd167(Integer td167) {
		this.td167 = td167;
	}

	@Column(name = "td168")
	public Integer getTd168() {
		return this.td168;
	}

	public void setTd168(Integer td168) {
		this.td168 = td168;
	}

	@Column(name = "td169")
	public Integer getTd169() {
		return this.td169;
	}

	public void setTd169(Integer td169) {
		this.td169 = td169;
	}

	@Column(name = "td170")
	public Integer getTd170() {
		return this.td170;
	}

	public void setTd170(Integer td170) {
		this.td170 = td170;
	}

	@Column(name = "td171")
	public Integer getTd171() {
		return this.td171;
	}

	public void setTd171(Integer td171) {
		this.td171 = td171;
	}

	@Column(name = "td172")
	public Integer getTd172() {
		return this.td172;
	}

	public void setTd172(Integer td172) {
		this.td172 = td172;
	}

	@Column(name = "td173")
	public Integer getTd173() {
		return this.td173;
	}

	public void setTd173(Integer td173) {
		this.td173 = td173;
	}

	@Column(name = "td174")
	public Integer getTd174() {
		return this.td174;
	}

	public void setTd174(Integer td174) {
		this.td174 = td174;
	}

	@Column(name = "td175")
	public Integer getTd175() {
		return this.td175;
	}

	public void setTd175(Integer td175) {
		this.td175 = td175;
	}

	@Column(name = "td176")
	public Integer getTd176() {
		return this.td176;
	}

	public void setTd176(Integer td176) {
		this.td176 = td176;
	}

	@Column(name = "td177")
	public Integer getTd177() {
		return this.td177;
	}

	public void setTd177(Integer td177) {
		this.td177 = td177;
	}

	@Column(name = "td178")
	public Integer getTd178() {
		return this.td178;
	}

	public void setTd178(Integer td178) {
		this.td178 = td178;
	}

	@Column(name = "td179")
	public Integer getTd179() {
		return this.td179;
	}

	public void setTd179(Integer td179) {
		this.td179 = td179;
	}

	@Column(name = "td180")
	public Integer getTd180() {
		return this.td180;
	}

	public void setTd180(Integer td180) {
		this.td180 = td180;
	}

	@Column(name = "td181")
	public Integer getTd181() {
		return this.td181;
	}

	public void setTd181(Integer td181) {
		this.td181 = td181;
	}

	@Column(name = "td182")
	public Integer getTd182() {
		return this.td182;
	}

	public void setTd182(Integer td182) {
		this.td182 = td182;
	}

	@Column(name = "td183")
	public Integer getTd183() {
		return this.td183;
	}

	public void setTd183(Integer td183) {
		this.td183 = td183;
	}

	@Column(name = "td184")
	public Integer getTd184() {
		return this.td184;
	}

	public void setTd184(Integer td184) {
		this.td184 = td184;
	}

	@Column(name = "td185")
	public Integer getTd185() {
		return this.td185;
	}

	public void setTd185(Integer td185) {
		this.td185 = td185;
	}

	@Column(name = "td186")
	public Integer getTd186() {
		return this.td186;
	}

	public void setTd186(Integer td186) {
		this.td186 = td186;
	}

	@Column(name = "td187")
	public Integer getTd187() {
		return this.td187;
	}

	public void setTd187(Integer td187) {
		this.td187 = td187;
	}

	@Column(name = "td188")
	public Integer getTd188() {
		return this.td188;
	}

	public void setTd188(Integer td188) {
		this.td188 = td188;
	}

	@Column(name = "td189")
	public Integer getTd189() {
		return this.td189;
	}

	public void setTd189(Integer td189) {
		this.td189 = td189;
	}

	@Column(name = "td190")
	public Integer getTd190() {
		return this.td190;
	}

	public void setTd190(Integer td190) {
		this.td190 = td190;
	}

	@Column(name = "td191")
	public Integer getTd191() {
		return this.td191;
	}

	public void setTd191(Integer td191) {
		this.td191 = td191;
	}

	@Column(name = "td192")
	public Integer getTd192() {
		return this.td192;
	}

	public void setTd192(Integer td192) {
		this.td192 = td192;
	}

	@Column(name = "td193")
	public Integer getTd193() {
		return this.td193;
	}

	public void setTd193(Integer td193) {
		this.td193 = td193;
	}

	@Column(name = "td194")
	public Integer getTd194() {
		return this.td194;
	}

	public void setTd194(Integer td194) {
		this.td194 = td194;
	}

	@Column(name = "td195")
	public Integer getTd195() {
		return this.td195;
	}

	public void setTd195(Integer td195) {
		this.td195 = td195;
	}

	@Column(name = "td196")
	public Integer getTd196() {
		return this.td196;
	}

	public void setTd196(Integer td196) {
		this.td196 = td196;
	}

	@Column(name = "td197")
	public Integer getTd197() {
		return this.td197;
	}

	public void setTd197(Integer td197) {
		this.td197 = td197;
	}

	@Column(name = "td198")
	public Integer getTd198() {
		return this.td198;
	}

	public void setTd198(Integer td198) {
		this.td198 = td198;
	}

	@Column(name = "td199")
	public Integer getTd199() {
		return this.td199;
	}

	public void setTd199(Integer td199) {
		this.td199 = td199;
	}

	@Column(name = "td200")
	public Integer getTd200() {
		return this.td200;
	}

	public void setTd200(Integer td200) {
		this.td200 = td200;
	}

	@Column(name = "td201")
	public Integer getTd201() {
		return this.td201;
	}

	public void setTd201(Integer td201) {
		this.td201 = td201;
	}

	@Column(name = "td202")
	public Integer getTd202() {
		return this.td202;
	}

	public void setTd202(Integer td202) {
		this.td202 = td202;
	}

	@Column(name = "td203")
	public Integer getTd203() {
		return this.td203;
	}

	public void setTd203(Integer td203) {
		this.td203 = td203;
	}

	@Column(name = "td204")
	public Integer getTd204() {
		return this.td204;
	}

	public void setTd204(Integer td204) {
		this.td204 = td204;
	}

	@Column(name = "td205")
	public Integer getTd205() {
		return this.td205;
	}

	public void setTd205(Integer td205) {
		this.td205 = td205;
	}

	@Column(name = "td206")
	public Integer getTd206() {
		return this.td206;
	}

	public void setTd206(Integer td206) {
		this.td206 = td206;
	}

	@Column(name = "td207")
	public Integer getTd207() {
		return this.td207;
	}

	public void setTd207(Integer td207) {
		this.td207 = td207;
	}

	@Column(name = "td208")
	public Integer getTd208() {
		return this.td208;
	}

	public void setTd208(Integer td208) {
		this.td208 = td208;
	}

	@Column(name = "td209")
	public Integer getTd209() {
		return this.td209;
	}

	public void setTd209(Integer td209) {
		this.td209 = td209;
	}

	@Column(name = "td210")
	public Integer getTd210() {
		return this.td210;
	}

	public void setTd210(Integer td210) {
		this.td210 = td210;
	}

	@Column(name = "td211")
	public Integer getTd211() {
		return this.td211;
	}

	public void setTd211(Integer td211) {
		this.td211 = td211;
	}

	@Column(name = "td212")
	public Integer getTd212() {
		return this.td212;
	}

	public void setTd212(Integer td212) {
		this.td212 = td212;
	}

	@Column(name = "td213")
	public Integer getTd213() {
		return this.td213;
	}

	public void setTd213(Integer td213) {
		this.td213 = td213;
	}

	@Column(name = "td214")
	public Integer getTd214() {
		return this.td214;
	}

	public void setTd214(Integer td214) {
		this.td214 = td214;
	}

	@Column(name = "td215")
	public Integer getTd215() {
		return this.td215;
	}

	public void setTd215(Integer td215) {
		this.td215 = td215;
	}

	@Column(name = "td216")
	public Integer getTd216() {
		return this.td216;
	}

	public void setTd216(Integer td216) {
		this.td216 = td216;
	}

	@Column(name = "td217")
	public Integer getTd217() {
		return this.td217;
	}

	public void setTd217(Integer td217) {
		this.td217 = td217;
	}

	@Column(name = "td218")
	public Integer getTd218() {
		return this.td218;
	}

	public void setTd218(Integer td218) {
		this.td218 = td218;
	}

	@Column(name = "td219")
	public Integer getTd219() {
		return this.td219;
	}

	public void setTd219(Integer td219) {
		this.td219 = td219;
	}

	@Column(name = "td220")
	public Integer getTd220() {
		return this.td220;
	}

	public void setTd220(Integer td220) {
		this.td220 = td220;
	}

	@Column(name = "td221")
	public Integer getTd221() {
		return this.td221;
	}

	public void setTd221(Integer td221) {
		this.td221 = td221;
	}

	@Column(name = "td222")
	public Integer getTd222() {
		return this.td222;
	}

	public void setTd222(Integer td222) {
		this.td222 = td222;
	}

	@Column(name = "td223")
	public Integer getTd223() {
		return this.td223;
	}

	public void setTd223(Integer td223) {
		this.td223 = td223;
	}

	@Column(name = "td224")
	public Integer getTd224() {
		return this.td224;
	}

	public void setTd224(Integer td224) {
		this.td224 = td224;
	}

	@Column(name = "td225")
	public Integer getTd225() {
		return this.td225;
	}

	public void setTd225(Integer td225) {
		this.td225 = td225;
	}

	@Column(name = "td226")
	public Integer getTd226() {
		return this.td226;
	}

	public void setTd226(Integer td226) {
		this.td226 = td226;
	}

	@Column(name = "td227")
	public Integer getTd227() {
		return this.td227;
	}

	public void setTd227(Integer td227) {
		this.td227 = td227;
	}

	@Column(name = "td228")
	public Integer getTd228() {
		return this.td228;
	}

	public void setTd228(Integer td228) {
		this.td228 = td228;
	}

	@Column(name = "td229")
	public Integer getTd229() {
		return this.td229;
	}

	public void setTd229(Integer td229) {
		this.td229 = td229;
	}

	@Column(name = "td230")
	public Integer getTd230() {
		return this.td230;
	}

	public void setTd230(Integer td230) {
		this.td230 = td230;
	}

	@Column(name = "td231")
	public Integer getTd231() {
		return this.td231;
	}

	public void setTd231(Integer td231) {
		this.td231 = td231;
	}

	@Column(name = "td232")
	public Integer getTd232() {
		return this.td232;
	}

	public void setTd232(Integer td232) {
		this.td232 = td232;
	}

	@Column(name = "td233")
	public Integer getTd233() {
		return this.td233;
	}

	public void setTd233(Integer td233) {
		this.td233 = td233;
	}

	@Column(name = "td234")
	public Integer getTd234() {
		return this.td234;
	}

	public void setTd234(Integer td234) {
		this.td234 = td234;
	}

	@Column(name = "td235")
	public Integer getTd235() {
		return this.td235;
	}

	public void setTd235(Integer td235) {
		this.td235 = td235;
	}

	@Column(name = "td236")
	public Integer getTd236() {
		return this.td236;
	}

	public void setTd236(Integer td236) {
		this.td236 = td236;
	}

	@Column(name = "td237")
	public Integer getTd237() {
		return this.td237;
	}

	public void setTd237(Integer td237) {
		this.td237 = td237;
	}

	@Column(name = "td238")
	public Integer getTd238() {
		return this.td238;
	}

	public void setTd238(Integer td238) {
		this.td238 = td238;
	}

	@Column(name = "td239")
	public Integer getTd239() {
		return this.td239;
	}

	public void setTd239(Integer td239) {
		this.td239 = td239;
	}

	@Column(name = "td240")
	public Integer getTd240() {
		return this.td240;
	}

	public void setTd240(Integer td240) {
		this.td240 = td240;
	}

}
