package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Projectquestion generated by hbm2java
 */
@Entity
@Table(name = "projectquestion", catalog = "audit")
public class ProjectQuestion implements java.io.Serializable {

	private int id;
	private Integer projectId;
	private String projectName;
	private String questionTitle;
	private String content;

	public ProjectQuestion() {
	}

	public ProjectQuestion(int id) {
		this.id = id;
	}

	public ProjectQuestion(int id, Integer projectId, String projectName, String questionTitle, String content) {
		this.id = id;
		this.projectId = projectId;
		this.projectName = projectName;
		this.questionTitle = questionTitle;
		this.content = content;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "projectId")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "projectName")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "questionTitle", length = 100)
	public String getQuestionTitle() {
		return this.questionTitle;
	}

	public void setQuestionTitle(String questionTitle) {
		this.questionTitle = questionTitle;
	}

	@Column(name = "content", length = 10000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
