package com.ky.ct.rzdj.model;
// Generated 2018-3-15 12:35:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Sysconfig generated by hbm2java
 */
@Entity
@Table(name = "sysconfig", catalog = "audit")
public class Sysconfig implements java.io.Serializable {

	private Integer id;
	private String itemType;
	private String itemKey;
	private String itemValue;
	private String remark;
	private Integer sortOrder;

	public Sysconfig() {
	}

	public Sysconfig(String itemType, String itemKey, String itemValue, String remark, Integer sortOrder) {
		this.itemType = itemType;
		this.itemKey = itemKey;
		this.itemValue = itemValue;
		this.remark = remark;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "itemType", length = 32)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Column(name = "itemKey", length = 32)
	public String getItemKey() {
		return this.itemKey;
	}

	public void setItemKey(String itemKey) {
		this.itemKey = itemKey;
	}

	@Column(name = "itemValue", length = 64)
	public String getItemValue() {
		return this.itemValue;
	}

	public void setItemValue(String itemValue) {
		this.itemValue = itemValue;
	}

	@Column(name = "remark", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "sortOrder")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
